// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: flotestro/helper/v1/helper.proto

package helperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalUserActionRequest_Operation int32

const (
	LocalUserActionRequest_OPERATION_UNSPECIFIED  LocalUserActionRequest_Operation = 0
	LocalUserActionRequest_OPERATION_CREATE       LocalUserActionRequest_Operation = 1
	LocalUserActionRequest_OPERATION_LOCK         LocalUserActionRequest_Operation = 2
	LocalUserActionRequest_OPERATION_UNLOCK       LocalUserActionRequest_Operation = 3
	LocalUserActionRequest_OPERATION_SET_SSH_KEYS LocalUserActionRequest_Operation = 4
)

// Enum value maps for LocalUserActionRequest_Operation.
var (
	LocalUserActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_LOCK",
		3: "OPERATION_UNLOCK",
		4: "OPERATION_SET_SSH_KEYS",
	}
	LocalUserActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":  0,
		"OPERATION_CREATE":       1,
		"OPERATION_LOCK":         2,
		"OPERATION_UNLOCK":       3,
		"OPERATION_SET_SSH_KEYS": 4,
	}
)

func (x LocalUserActionRequest_Operation) Enum() *LocalUserActionRequest_Operation {
	p := new(LocalUserActionRequest_Operation)
	*p = x
	return p
}

func (x LocalUserActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalUserActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[0].Descriptor()
}

func (LocalUserActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[0]
}

func (x LocalUserActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalUserActionRequest_Operation.Descriptor instead.
func (LocalUserActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{2, 0}
}

type PackageActionRequest_Operation int32

const (
	PackageActionRequest_OPERATION_UNSPECIFIED PackageActionRequest_Operation = 0
	// Odswiezenie metadanych repozytorium.
	PackageActionRequest_OPERATION_REFRESH PackageActionRequest_Operation = 1
	// Wykonanie transakcji aktualizacji.
	PackageActionRequest_OPERATION_UPGRADE PackageActionRequest_Operation = 2
)

// Enum value maps for PackageActionRequest_Operation.
var (
	PackageActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_REFRESH",
		2: "OPERATION_UPGRADE",
	}
	PackageActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_REFRESH":     1,
		"OPERATION_UPGRADE":     2,
	}
)

func (x PackageActionRequest_Operation) Enum() *PackageActionRequest_Operation {
	p := new(PackageActionRequest_Operation)
	*p = x
	return p
}

func (x PackageActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[1].Descriptor()
}

func (PackageActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[1]
}

func (x PackageActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageActionRequest_Operation.Descriptor instead.
func (PackageActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{6, 0}
}

type UnitActionRequest_Operation int32

const (
	UnitActionRequest_OPERATION_UNSPECIFIED UnitActionRequest_Operation = 0
	UnitActionRequest_OPERATION_START       UnitActionRequest_Operation = 1
	UnitActionRequest_OPERATION_STOP        UnitActionRequest_Operation = 2
	UnitActionRequest_OPERATION_RESTART     UnitActionRequest_Operation = 3
	UnitActionRequest_OPERATION_RELOAD      UnitActionRequest_Operation = 4
)

// Enum value maps for UnitActionRequest_Operation.
var (
	UnitActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_START",
		2: "OPERATION_STOP",
		3: "OPERATION_RESTART",
		4: "OPERATION_RELOAD",
	}
	UnitActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_START":       1,
		"OPERATION_STOP":        2,
		"OPERATION_RESTART":     3,
		"OPERATION_RELOAD":      4,
	}
)

func (x UnitActionRequest_Operation) Enum() *UnitActionRequest_Operation {
	p := new(UnitActionRequest_Operation)
	*p = x
	return p
}

func (x UnitActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[2].Descriptor()
}

func (UnitActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[2]
}

func (x UnitActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitActionRequest_Operation.Descriptor instead.
func (UnitActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{7, 0}
}

// PROTOCOL_VERSION zmienia sie przy kazdej niezgodnej zmianie kontraktu.
// Helper odrzuca wersje, ktorej nie zna, zamiast zgadywac znaczenie pol.
type HelperRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Helper odrzuca zadanie po terminie, niezaleznie od tego, co twierdzi agent.
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxOutputBytes uint32                 `protobuf:"varint,5,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*HelperRequest_UnitAction
	//	*HelperRequest_PackageAction
	//	*HelperRequest_Reboot
	//	*HelperRequest_IdentityProbe
	//	*HelperRequest_DomainEnroll
	//	*HelperRequest_LocalAccounts
	//	*HelperRequest_LocalUserAction
	Action        isHelperRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperRequest) Reset() {
	*x = HelperRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperRequest) ProtoMessage() {}

func (x *HelperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperRequest.ProtoReflect.Descriptor instead.
func (*HelperRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{0}
}

func (x *HelperRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelperRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HelperRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *HelperRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HelperRequest) GetMaxOutputBytes() uint32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *HelperRequest) GetAction() isHelperRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *HelperRequest) GetUnitAction() *UnitActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_UnitAction); ok {
			return x.UnitAction
		}
	}
	return nil
}

func (x *HelperRequest) GetPackageAction() *PackageActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_PackageAction); ok {
			return x.PackageAction
		}
	}
	return nil
}

func (x *HelperRequest) GetReboot() *RebootRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *HelperRequest) GetIdentityProbe() *IdentityProbeRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_IdentityProbe); ok {
			return x.IdentityProbe
		}
	}
	return nil
}

func (x *HelperRequest) GetDomainEnroll() *DomainEnrollRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_DomainEnroll); ok {
			return x.DomainEnroll
		}
	}
	return nil
}

func (x *HelperRequest) GetLocalAccounts() *LocalAccountsRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_LocalAccounts); ok {
			return x.LocalAccounts
		}
	}
	return nil
}

func (x *HelperRequest) GetLocalUserAction() *LocalUserActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_LocalUserAction); ok {
			return x.LocalUserAction
		}
	}
	return nil
}

type isHelperRequest_Action interface {
	isHelperRequest_Action()
}

type HelperRequest_UnitAction struct {
	UnitAction *UnitActionRequest `protobuf:"bytes,20,opt,name=unit_action,json=unitAction,proto3,oneof"`
}

type HelperRequest_PackageAction struct {
	PackageAction *PackageActionRequest `protobuf:"bytes,21,opt,name=package_action,json=packageAction,proto3,oneof"`
}

type HelperRequest_Reboot struct {
	Reboot *RebootRequest `protobuf:"bytes,22,opt,name=reboot,proto3,oneof"`
}

type HelperRequest_IdentityProbe struct {
	IdentityProbe *IdentityProbeRequest `protobuf:"bytes,23,opt,name=identity_probe,json=identityProbe,proto3,oneof"`
}

type HelperRequest_DomainEnroll struct {
	DomainEnroll *DomainEnrollRequest `protobuf:"bytes,24,opt,name=domain_enroll,json=domainEnroll,proto3,oneof"`
}

type HelperRequest_LocalAccounts struct {
	LocalAccounts *LocalAccountsRequest `protobuf:"bytes,25,opt,name=local_accounts,json=localAccounts,proto3,oneof"`
}

type HelperRequest_LocalUserAction struct {
	LocalUserAction *LocalUserActionRequest `protobuf:"bytes,26,opt,name=local_user_action,json=localUserAction,proto3,oneof"`
}

func (*HelperRequest_UnitAction) isHelperRequest_Action() {}

func (*HelperRequest_PackageAction) isHelperRequest_Action() {}

func (*HelperRequest_Reboot) isHelperRequest_Action() {}

func (*HelperRequest_IdentityProbe) isHelperRequest_Action() {}

func (*HelperRequest_DomainEnroll) isHelperRequest_Action() {}

func (*HelperRequest_LocalAccounts) isHelperRequest_Action() {}

func (*HelperRequest_LocalUserAction) isHelperRequest_Action() {}

// LocalAccountsRequest odczytuje te dane o kontach, ktore wymagaja roota:
// stan blokady z /etc/shadow i klucze SSH z katalogow domowych.
type LocalAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalAccountsRequest) Reset() {
	*x = LocalAccountsRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAccountsRequest) ProtoMessage() {}

func (x *LocalAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAccountsRequest.ProtoReflect.Descriptor instead.
func (*LocalAccountsRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{1}
}

func (x *LocalAccountsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// LocalUserActionRequest zmienia konto lokalne na hoscie.
type LocalUserActionRequest struct {
	state     protoimpl.MessageState           `protogen:"open.v1"`
	Operation LocalUserActionRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=flotestro.helper.v1.LocalUserActionRequest_Operation" json:"operation,omitempty"`
	Name      string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gecos     string                           `protobuf:"bytes,3,opt,name=gecos,proto3" json:"gecos,omitempty"`
	Shell     string                           `protobuf:"bytes,4,opt,name=shell,proto3" json:"shell,omitempty"`
	Groups    []string                         `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	// Klucze publiczne w postaci pelnej. Klucz prywatny nigdy nie trafia
	// do systemu, a hasla nie sa przesylane w ogole.
	SshKeys []string `protobuf:"bytes,6,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	// CreateHome tworzy katalog domowy przy zakladaniu konta.
	CreateHome    bool `protobuf:"varint,7,opt,name=create_home,json=createHome,proto3" json:"create_home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalUserActionRequest) Reset() {
	*x = LocalUserActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalUserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUserActionRequest) ProtoMessage() {}

func (x *LocalUserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUserActionRequest.ProtoReflect.Descriptor instead.
func (*LocalUserActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{2}
}

func (x *LocalUserActionRequest) GetOperation() LocalUserActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return LocalUserActionRequest_OPERATION_UNSPECIFIED
}

func (x *LocalUserActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalUserActionRequest) GetGecos() string {
	if x != nil {
		return x.Gecos
	}
	return ""
}

func (x *LocalUserActionRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *LocalUserActionRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *LocalUserActionRequest) GetSshKeys() []string {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

func (x *LocalUserActionRequest) GetCreateHome() bool {
	if x != nil {
		return x.CreateHome
	}
	return false
}

// DomainEnrollRequest dolacza hosta do domeny. Wymaga roota, bo zmienia
// konfiguracje SSSD, Kerberosa i PAM.
type DomainEnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Domain          string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Realm           string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Server          string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	OneTimePassword string                 `protobuf:"bytes,4,opt,name=one_time_password,json=oneTimePassword,proto3" json:"one_time_password,omitempty"`
	Hostname        string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PreflightOnly   bool                   `protobuf:"varint,6,opt,name=preflight_only,json=preflightOnly,proto3" json:"preflight_only,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DomainEnrollRequest) Reset() {
	*x = DomainEnrollRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEnrollRequest) ProtoMessage() {}

func (x *DomainEnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEnrollRequest.ProtoReflect.Descriptor instead.
func (*DomainEnrollRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{3}
}

func (x *DomainEnrollRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainEnrollRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *DomainEnrollRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *DomainEnrollRequest) GetOneTimePassword() string {
	if x != nil {
		return x.OneTimePassword
	}
	return ""
}

func (x *DomainEnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DomainEnrollRequest) GetPreflightOnly() bool {
	if x != nil {
		return x.PreflightOnly
	}
	return false
}

// IdentityProbeRequest odczytuje te elementy stanu domeny, ktore wymagaja
// roota: keytab hosta i baze cache SSSD. Reszte agent czyta sam.
type IdentityProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityProbeRequest) Reset() {
	*x = IdentityProbeRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProbeRequest) ProtoMessage() {}

func (x *IdentityProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProbeRequest.ProtoReflect.Descriptor instead.
func (*IdentityProbeRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityProbeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// RebootRequest zleca kontrolowany restart hosta.
type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{5}
}

func (x *RebootRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *RebootRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PackageActionRequest obejmuje operacje pakietowe wymagajace roota.
// Planowanie w trybie symulacji nie wymaga roota i nie idzie przez helper.
type PackageActionRequest struct {
	state     protoimpl.MessageState         `protogen:"open.v1"`
	Operation PackageActionRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=flotestro.helper.v1.PackageActionRequest_Operation" json:"operation,omitempty"`
	// Pusta lista przy OPERATION_UPGRADE oznacza wszystkie aktualizacje.
	Packages      []string `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	SecurityOnly  bool     `protobuf:"varint,3,opt,name=security_only,json=securityOnly,proto3" json:"security_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageActionRequest) Reset() {
	*x = PackageActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageActionRequest) ProtoMessage() {}

func (x *PackageActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageActionRequest.ProtoReflect.Descriptor instead.
func (*PackageActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{6}
}

func (x *PackageActionRequest) GetOperation() PackageActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return PackageActionRequest_OPERATION_UNSPECIFIED
}

func (x *PackageActionRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackageActionRequest) GetSecurityOnly() bool {
	if x != nil {
		return x.SecurityOnly
	}
	return false
}

type UnitActionRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Unit          string                      `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Operation     UnitActionRequest_Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=flotestro.helper.v1.UnitActionRequest_Operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitActionRequest) Reset() {
	*x = UnitActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitActionRequest) ProtoMessage() {}

func (x *UnitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitActionRequest.ProtoReflect.Descriptor instead.
func (*UnitActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{7}
}

func (x *UnitActionRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitActionRequest) GetOperation() UnitActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return UnitActionRequest_OPERATION_UNSPECIFIED
}

type HelperResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Stabilny kod maszynowy: unknown_action, unsupported_version, expired,
	// protected_unit, invalid_unit, locked, exec_failed, timeout.
	ErrorCode       string               `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode        int32                `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          []byte               `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          []byte               `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	OutputTruncated bool                 `protobuf:"varint,7,opt,name=output_truncated,json=outputTruncated,proto3" json:"output_truncated,omitempty"`
	StateBefore     *UnitState           `protobuf:"bytes,8,opt,name=state_before,json=stateBefore,proto3" json:"state_before,omitempty"`
	StateAfter      *UnitState           `protobuf:"bytes,9,opt,name=state_after,json=stateAfter,proto3" json:"state_after,omitempty"`
	PackageResult   *PackageActionResult `protobuf:"bytes,10,opt,name=package_result,json=packageResult,proto3" json:"package_result,omitempty"`
	IdentityResult  *IdentityProbeResult `protobuf:"bytes,11,opt,name=identity_result,json=identityResult,proto3" json:"identity_result,omitempty"`
	EnrollResult    *DomainEnrollResult  `protobuf:"bytes,12,opt,name=enroll_result,json=enrollResult,proto3" json:"enroll_result,omitempty"`
	AccountsResult  *LocalAccountsResult `protobuf:"bytes,13,opt,name=accounts_result,json=accountsResult,proto3" json:"accounts_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelperResponse) Reset() {
	*x = HelperResponse{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperResponse) ProtoMessage() {}

func (x *HelperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperResponse.ProtoReflect.Descriptor instead.
func (*HelperResponse) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{8}
}

func (x *HelperResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelperResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *HelperResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelperResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *HelperResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *HelperResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *HelperResponse) GetOutputTruncated() bool {
	if x != nil {
		return x.OutputTruncated
	}
	return false
}

func (x *HelperResponse) GetStateBefore() *UnitState {
	if x != nil {
		return x.StateBefore
	}
	return nil
}

func (x *HelperResponse) GetStateAfter() *UnitState {
	if x != nil {
		return x.StateAfter
	}
	return nil
}

func (x *HelperResponse) GetPackageResult() *PackageActionResult {
	if x != nil {
		return x.PackageResult
	}
	return nil
}

func (x *HelperResponse) GetIdentityResult() *IdentityProbeResult {
	if x != nil {
		return x.IdentityResult
	}
	return nil
}

func (x *HelperResponse) GetEnrollResult() *DomainEnrollResult {
	if x != nil {
		return x.EnrollResult
	}
	return nil
}

func (x *HelperResponse) GetAccountsResult() *LocalAccountsResult {
	if x != nil {
		return x.AccountsResult
	}
	return nil
}

type LocalAccountsResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accounts          []*LocalAccountDetail  `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	UnavailableReason string                 `protobuf:"bytes,2,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocalAccountsResult) Reset() {
	*x = LocalAccountsResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAccountsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAccountsResult) ProtoMessage() {}

func (x *LocalAccountsResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAccountsResult.ProtoReflect.Descriptor instead.
func (*LocalAccountsResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{9}
}

func (x *LocalAccountsResult) GetAccounts() []*LocalAccountDetail {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *LocalAccountsResult) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type LocalAccountDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Locked        *bool                  `protobuf:"varint,2,opt,name=locked,proto3,oneof" json:"locked,omitempty"`
	SshKeys       []*LocalSSHKey         `protobuf:"bytes,3,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	PasswordSet   *bool                  `protobuf:"varint,4,opt,name=password_set,json=passwordSet,proto3,oneof" json:"password_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalAccountDetail) Reset() {
	*x = LocalAccountDetail{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAccountDetail) ProtoMessage() {}

func (x *LocalAccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAccountDetail.ProtoReflect.Descriptor instead.
func (*LocalAccountDetail) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{10}
}

func (x *LocalAccountDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalAccountDetail) GetLocked() bool {
	if x != nil && x.Locked != nil {
		return *x.Locked
	}
	return false
}

func (x *LocalAccountDetail) GetSshKeys() []*LocalSSHKey {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

func (x *LocalAccountDetail) GetPasswordSet() bool {
	if x != nil && x.PasswordSet != nil {
		return *x.PasswordSet
	}
	return false
}

type LocalSSHKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalSSHKey) Reset() {
	*x = LocalSSHKey{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSSHKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSSHKey) ProtoMessage() {}

func (x *LocalSSHKey) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSSHKey.ProtoReflect.Descriptor instead.
func (*LocalSSHKey) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{11}
}

func (x *LocalSSHKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *LocalSSHKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LocalSSHKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DomainEnrollResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*EnrollCheck         `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	Enrolled      bool                   `protobuf:"varint,2,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	HostPrincipal string                 `protobuf:"bytes,3,opt,name=host_principal,json=hostPrincipal,proto3" json:"host_principal,omitempty"`
	Verifications []*EnrollCheck         `protobuf:"bytes,4,rep,name=verifications,proto3" json:"verifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEnrollResult) Reset() {
	*x = DomainEnrollResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEnrollResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEnrollResult) ProtoMessage() {}

func (x *DomainEnrollResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEnrollResult.ProtoReflect.Descriptor instead.
func (*DomainEnrollResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{12}
}

func (x *DomainEnrollResult) GetChecks() []*EnrollCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *DomainEnrollResult) GetEnrolled() bool {
	if x != nil {
		return x.Enrolled
	}
	return false
}

func (x *DomainEnrollResult) GetHostPrincipal() string {
	if x != nil {
		return x.HostPrincipal
	}
	return ""
}

func (x *DomainEnrollResult) GetVerifications() []*EnrollCheck {
	if x != nil {
		return x.Verifications
	}
	return nil
}

type EnrollCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passed        *bool                  `protobuf:"varint,2,opt,name=passed,proto3,oneof" json:"passed,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Blocking      bool                   `protobuf:"varint,4,opt,name=blocking,proto3" json:"blocking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollCheck) Reset() {
	*x = EnrollCheck{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCheck) ProtoMessage() {}

func (x *EnrollCheck) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCheck.ProtoReflect.Descriptor instead.
func (*EnrollCheck) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{13}
}

func (x *EnrollCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollCheck) GetPassed() bool {
	if x != nil && x.Passed != nil {
		return *x.Passed
	}
	return false
}

func (x *EnrollCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *EnrollCheck) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

type IdentityProbeResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostPrincipal   string                 `protobuf:"bytes,1,opt,name=host_principal,json=hostPrincipal,proto3" json:"host_principal,omitempty"`
	KeytabKvno      *uint32                `protobuf:"varint,2,opt,name=keytab_kvno,json=keytabKvno,proto3,oneof" json:"keytab_kvno,omitempty"`
	CacheAgeSeconds *uint64                `protobuf:"varint,3,opt,name=cache_age_seconds,json=cacheAgeSeconds,proto3,oneof" json:"cache_age_seconds,omitempty"`
	SssdOnline      *bool                  `protobuf:"varint,4,opt,name=sssd_online,json=sssdOnline,proto3,oneof" json:"sssd_online,omitempty"`
	ConfigIssues    []string               `protobuf:"bytes,5,rep,name=config_issues,json=configIssues,proto3" json:"config_issues,omitempty"`
	// Powod, dla ktorego czesci stanu nie udalo sie ustalic.
	UnavailableReason string `protobuf:"bytes,6,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IdentityProbeResult) Reset() {
	*x = IdentityProbeResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProbeResult) ProtoMessage() {}

func (x *IdentityProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProbeResult.ProtoReflect.Descriptor instead.
func (*IdentityProbeResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{14}
}

func (x *IdentityProbeResult) GetHostPrincipal() string {
	if x != nil {
		return x.HostPrincipal
	}
	return ""
}

func (x *IdentityProbeResult) GetKeytabKvno() uint32 {
	if x != nil && x.KeytabKvno != nil {
		return *x.KeytabKvno
	}
	return 0
}

func (x *IdentityProbeResult) GetCacheAgeSeconds() uint64 {
	if x != nil && x.CacheAgeSeconds != nil {
		return *x.CacheAgeSeconds
	}
	return 0
}

func (x *IdentityProbeResult) GetSssdOnline() bool {
	if x != nil && x.SssdOnline != nil {
		return *x.SssdOnline
	}
	return false
}

func (x *IdentityProbeResult) GetConfigIssues() []string {
	if x != nil {
		return x.ConfigIssues
	}
	return nil
}

func (x *IdentityProbeResult) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type PackageActionResult struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Manager                string                  `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	Applied                []*PackageVersionChange `protobuf:"bytes,2,rep,name=applied,proto3" json:"applied,omitempty"`
	RebootRequired         bool                    `protobuf:"varint,3,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	ServicesNeedingRestart []string                `protobuf:"bytes,4,rep,name=services_needing_restart,json=servicesNeedingRestart,proto3" json:"services_needing_restart,omitempty"`
	// Prawda, gdy baza pakietow wymaga naprawy po nieudanej transakcji.
	PackageDatabaseBroken bool `protobuf:"varint,5,opt,name=package_database_broken,json=packageDatabaseBroken,proto3" json:"package_database_broken,omitempty"`
	// Pakiety, ktore czekaja na dokonczenie konfiguracji albo sa uszkodzone.
	PackagesNeedingAttention []string `protobuf:"bytes,6,rep,name=packages_needing_attention,json=packagesNeedingAttention,proto3" json:"packages_needing_attention,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PackageActionResult) Reset() {
	*x = PackageActionResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageActionResult) ProtoMessage() {}

func (x *PackageActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageActionResult.ProtoReflect.Descriptor instead.
func (*PackageActionResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{15}
}

func (x *PackageActionResult) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *PackageActionResult) GetApplied() []*PackageVersionChange {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *PackageActionResult) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *PackageActionResult) GetServicesNeedingRestart() []string {
	if x != nil {
		return x.ServicesNeedingRestart
	}
	return nil
}

func (x *PackageActionResult) GetPackageDatabaseBroken() bool {
	if x != nil {
		return x.PackageDatabaseBroken
	}
	return false
}

func (x *PackageActionResult) GetPackagesNeedingAttention() []string {
	if x != nil {
		return x.PackagesNeedingAttention
	}
	return nil
}

type PackageVersionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionBefore string                 `protobuf:"bytes,2,opt,name=version_before,json=versionBefore,proto3" json:"version_before,omitempty"`
	VersionAfter  string                 `protobuf:"bytes,3,opt,name=version_after,json=versionAfter,proto3" json:"version_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageVersionChange) Reset() {
	*x = PackageVersionChange{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageVersionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageVersionChange) ProtoMessage() {}

func (x *PackageVersionChange) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageVersionChange.ProtoReflect.Descriptor instead.
func (*PackageVersionChange) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{16}
}

func (x *PackageVersionChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageVersionChange) GetVersionBefore() string {
	if x != nil {
		return x.VersionBefore
	}
	return ""
}

func (x *PackageVersionChange) GetVersionAfter() string {
	if x != nil {
		return x.VersionAfter
	}
	return ""
}

type UnitState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LoadState     string                 `protobuf:"bytes,2,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	ActiveState   string                 `protobuf:"bytes,3,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	SubState      string                 `protobuf:"bytes,4,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`
	UnitFileState string                 `protobuf:"bytes,5,opt,name=unit_file_state,json=unitFileState,proto3" json:"unit_file_state,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	MainPid       uint32                 `protobuf:"varint,7,opt,name=main_pid,json=mainPid,proto3" json:"main_pid,omitempty"`
	NRestarts     uint32                 `protobuf:"varint,8,opt,name=n_restarts,json=nRestarts,proto3" json:"n_restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitState) Reset() {
	*x = UnitState{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitState) ProtoMessage() {}

func (x *UnitState) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitState.ProtoReflect.Descriptor instead.
func (*UnitState) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{17}
}

func (x *UnitState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitState) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *UnitState) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *UnitState) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *UnitState) GetUnitFileState() string {
	if x != nil {
		return x.UnitFileState
	}
	return ""
}

func (x *UnitState) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *UnitState) GetMainPid() uint32 {
	if x != nil {
		return x.MainPid
	}
	return 0
}

func (x *UnitState) GetNRestarts() uint32 {
	if x != nil {
		return x.NRestarts
	}
	return 0
}

var File_flotestro_helper_v1_helper_proto protoreflect.FileDescriptor

const file_flotestro_helper_v1_helper_proto_rawDesc = "" +
	"\n" +
	" flotestro/helper/v1/helper.proto\x12\x13flotestro.helper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x06\n" +
	"\rHelperRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12(\n" +
	"\x10max_output_bytes\x18\x05 \x01(\rR\x0emaxOutputBytes\x12I\n" +
	"\vunit_action\x18\x14 \x01(\v2&.flotestro.helper.v1.UnitActionRequestH\x00R\n" +
	"unitAction\x12R\n" +
	"\x0epackage_action\x18\x15 \x01(\v2).flotestro.helper.v1.PackageActionRequestH\x00R\rpackageAction\x12<\n" +
	"\x06reboot\x18\x16 \x01(\v2\".flotestro.helper.v1.RebootRequestH\x00R\x06reboot\x12R\n" +
	"\x0eidentity_probe\x18\x17 \x01(\v2).flotestro.helper.v1.IdentityProbeRequestH\x00R\ridentityProbe\x12O\n" +
	"\rdomain_enroll\x18\x18 \x01(\v2(.flotestro.helper.v1.DomainEnrollRequestH\x00R\fdomainEnroll\x12R\n" +
	"\x0elocal_accounts\x18\x19 \x01(\v2).flotestro.helper.v1.LocalAccountsRequestH\x00R\rlocalAccounts\x12Y\n" +
	"\x11local_user_action\x18\x1a \x01(\v2+.flotestro.helper.v1.LocalUserActionRequestH\x00R\x0flocalUserActionB\b\n" +
	"\x06action\",\n" +
	"\x14LocalAccountsRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x86\x03\n" +
	"\x16LocalUserActionRequest\x12S\n" +
	"\toperation\x18\x01 \x01(\x0e25.flotestro.helper.v1.LocalUserActionRequest.OperationR\toperation\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05gecos\x18\x03 \x01(\tR\x05gecos\x12\x14\n" +
	"\x05shell\x18\x04 \x01(\tR\x05shell\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\tR\x06groups\x12\x19\n" +
	"\bssh_keys\x18\x06 \x03(\tR\asshKeys\x12\x1f\n" +
	"\vcreate_home\x18\a \x01(\bR\n" +
	"createHome\"\x82\x01\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x12\n" +
	"\x0eOPERATION_LOCK\x10\x02\x12\x14\n" +
	"\x10OPERATION_UNLOCK\x10\x03\x12\x1a\n" +
	"\x16OPERATION_SET_SSH_KEYS\x10\x04\"\xca\x01\n" +
	"\x13DomainEnrollRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12*\n" +
	"\x11one_time_password\x18\x04 \x01(\tR\x0foneTimePassword\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12%\n" +
	"\x0epreflight_only\x18\x06 \x01(\bR\rpreflightOnly\".\n" +
	"\x14IdentityProbeRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"L\n" +
	"\rRebootRequest\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x80\x02\n" +
	"\x14PackageActionRequest\x12Q\n" +
	"\toperation\x18\x01 \x01(\x0e23.flotestro.helper.v1.PackageActionRequest.OperationR\toperation\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\x12#\n" +
	"\rsecurity_only\x18\x03 \x01(\bR\fsecurityOnly\"T\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OPERATION_REFRESH\x10\x01\x12\x15\n" +
	"\x11OPERATION_UPGRADE\x10\x02\"\xf5\x01\n" +
	"\x11UnitActionRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12N\n" +
	"\toperation\x18\x02 \x01(\x0e20.flotestro.helper.v1.UnitActionRequest.OperationR\toperation\"|\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_START\x10\x01\x12\x12\n" +
	"\x0eOPERATION_STOP\x10\x02\x12\x15\n" +
	"\x11OPERATION_RESTART\x10\x03\x12\x14\n" +
	"\x10OPERATION_RELOAD\x10\x04\"\xa6\x05\n" +
	"\x0eHelperResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\fR\x06stderr\x12)\n" +
	"\x10output_truncated\x18\a \x01(\bR\x0foutputTruncated\x12A\n" +
	"\fstate_before\x18\b \x01(\v2\x1e.flotestro.helper.v1.UnitStateR\vstateBefore\x12?\n" +
	"\vstate_after\x18\t \x01(\v2\x1e.flotestro.helper.v1.UnitStateR\n" +
	"stateAfter\x12O\n" +
	"\x0epackage_result\x18\n" +
	" \x01(\v2(.flotestro.helper.v1.PackageActionResultR\rpackageResult\x12Q\n" +
	"\x0fidentity_result\x18\v \x01(\v2(.flotestro.helper.v1.IdentityProbeResultR\x0eidentityResult\x12L\n" +
	"\renroll_result\x18\f \x01(\v2'.flotestro.helper.v1.DomainEnrollResultR\fenrollResult\x12Q\n" +
	"\x0faccounts_result\x18\r \x01(\v2(.flotestro.helper.v1.LocalAccountsResultR\x0eaccountsResult\"\x89\x01\n" +
	"\x13LocalAccountsResult\x12C\n" +
	"\baccounts\x18\x01 \x03(\v2'.flotestro.helper.v1.LocalAccountDetailR\baccounts\x12-\n" +
	"\x12unavailable_reason\x18\x02 \x01(\tR\x11unavailableReason\"\xc6\x01\n" +
	"\x12LocalAccountDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\x06locked\x18\x02 \x01(\bH\x00R\x06locked\x88\x01\x01\x12;\n" +
	"\bssh_keys\x18\x03 \x03(\v2 .flotestro.helper.v1.LocalSSHKeyR\asshKeys\x12&\n" +
	"\fpassword_set\x18\x04 \x01(\bH\x01R\vpasswordSet\x88\x01\x01B\t\n" +
	"\a_lockedB\x0f\n" +
	"\r_password_set\"]\n" +
	"\vLocalSSHKey\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\xd9\x01\n" +
	"\x12DomainEnrollResult\x128\n" +
	"\x06checks\x18\x01 \x03(\v2 .flotestro.helper.v1.EnrollCheckR\x06checks\x12\x1a\n" +
	"\benrolled\x18\x02 \x01(\bR\benrolled\x12%\n" +
	"\x0ehost_principal\x18\x03 \x01(\tR\rhostPrincipal\x12F\n" +
	"\rverifications\x18\x04 \x03(\v2 .flotestro.helper.v1.EnrollCheckR\rverifications\"}\n" +
	"\vEnrollCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\x06passed\x18\x02 \x01(\bH\x00R\x06passed\x88\x01\x01\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1a\n" +
	"\bblocking\x18\x04 \x01(\bR\bblockingB\t\n" +
	"\a_passed\"\xc3\x02\n" +
	"\x13IdentityProbeResult\x12%\n" +
	"\x0ehost_principal\x18\x01 \x01(\tR\rhostPrincipal\x12$\n" +
	"\vkeytab_kvno\x18\x02 \x01(\rH\x00R\n" +
	"keytabKvno\x88\x01\x01\x12/\n" +
	"\x11cache_age_seconds\x18\x03 \x01(\x04H\x01R\x0fcacheAgeSeconds\x88\x01\x01\x12$\n" +
	"\vsssd_online\x18\x04 \x01(\bH\x02R\n" +
	"sssdOnline\x88\x01\x01\x12#\n" +
	"\rconfig_issues\x18\x05 \x03(\tR\fconfigIssues\x12-\n" +
	"\x12unavailable_reason\x18\x06 \x01(\tR\x11unavailableReasonB\x0e\n" +
	"\f_keytab_kvnoB\x14\n" +
	"\x12_cache_age_secondsB\x0e\n" +
	"\f_sssd_online\"\xcd\x02\n" +
	"\x13PackageActionResult\x12\x18\n" +
	"\amanager\x18\x01 \x01(\tR\amanager\x12C\n" +
	"\aapplied\x18\x02 \x03(\v2).flotestro.helper.v1.PackageVersionChangeR\aapplied\x12'\n" +
	"\x0freboot_required\x18\x03 \x01(\bR\x0erebootRequired\x128\n" +
	"\x18services_needing_restart\x18\x04 \x03(\tR\x16servicesNeedingRestart\x126\n" +
	"\x17package_database_broken\x18\x05 \x01(\bR\x15packageDatabaseBroken\x12<\n" +
	"\x1apackages_needing_attention\x18\x06 \x03(\tR\x18packagesNeedingAttention\"v\n" +
	"\x14PackageVersionChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eversion_before\x18\x02 \x01(\tR\rversionBefore\x12#\n" +
	"\rversion_after\x18\x03 \x01(\tR\fversionAfter\"\xf8\x01\n" +
	"\tUnitState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"load_state\x18\x02 \x01(\tR\tloadState\x12!\n" +
	"\factive_state\x18\x03 \x01(\tR\vactiveState\x12\x1b\n" +
	"\tsub_state\x18\x04 \x01(\tR\bsubState\x12&\n" +
	"\x0funit_file_state\x18\x05 \x01(\tR\runitFileState\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x19\n" +
	"\bmain_pid\x18\a \x01(\rR\amainPid\x12\x1d\n" +
	"\n" +
	"n_restarts\x18\b \x01(\rR\tnRestartsBOZMgithub.com/ultherego/flotestro/internal/genproto/flotestro/helper/v1;helperv1b\x06proto3"

var (
	file_flotestro_helper_v1_helper_proto_rawDescOnce sync.Once
	file_flotestro_helper_v1_helper_proto_rawDescData []byte
)

func file_flotestro_helper_v1_helper_proto_rawDescGZIP() []byte {
	file_flotestro_helper_v1_helper_proto_rawDescOnce.Do(func() {
		file_flotestro_helper_v1_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flotestro_helper_v1_helper_proto_rawDesc), len(file_flotestro_helper_v1_helper_proto_rawDesc)))
	})
	return file_flotestro_helper_v1_helper_proto_rawDescData
}

var file_flotestro_helper_v1_helper_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_flotestro_helper_v1_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_flotestro_helper_v1_helper_proto_goTypes = []any{
	(LocalUserActionRequest_Operation)(0), // 0: flotestro.helper.v1.LocalUserActionRequest.Operation
	(PackageActionRequest_Operation)(0),   // 1: flotestro.helper.v1.PackageActionRequest.Operation
	(UnitActionRequest_Operation)(0),      // 2: flotestro.helper.v1.UnitActionRequest.Operation
	(*HelperRequest)(nil),                 // 3: flotestro.helper.v1.HelperRequest
	(*LocalAccountsRequest)(nil),          // 4: flotestro.helper.v1.LocalAccountsRequest
	(*LocalUserActionRequest)(nil),        // 5: flotestro.helper.v1.LocalUserActionRequest
	(*DomainEnrollRequest)(nil),           // 6: flotestro.helper.v1.DomainEnrollRequest
	(*IdentityProbeRequest)(nil),          // 7: flotestro.helper.v1.IdentityProbeRequest
	(*RebootRequest)(nil),                 // 8: flotestro.helper.v1.RebootRequest
	(*PackageActionRequest)(nil),          // 9: flotestro.helper.v1.PackageActionRequest
	(*UnitActionRequest)(nil),             // 10: flotestro.helper.v1.UnitActionRequest
	(*HelperResponse)(nil),                // 11: flotestro.helper.v1.HelperResponse
	(*LocalAccountsResult)(nil),           // 12: flotestro.helper.v1.LocalAccountsResult
	(*LocalAccountDetail)(nil),            // 13: flotestro.helper.v1.LocalAccountDetail
	(*LocalSSHKey)(nil),                   // 14: flotestro.helper.v1.LocalSSHKey
	(*DomainEnrollResult)(nil),            // 15: flotestro.helper.v1.DomainEnrollResult
	(*EnrollCheck)(nil),                   // 16: flotestro.helper.v1.EnrollCheck
	(*IdentityProbeResult)(nil),           // 17: flotestro.helper.v1.IdentityProbeResult
	(*PackageActionResult)(nil),           // 18: flotestro.helper.v1.PackageActionResult
	(*PackageVersionChange)(nil),          // 19: flotestro.helper.v1.PackageVersionChange
	(*UnitState)(nil),                     // 20: flotestro.helper.v1.UnitState
	(*timestamppb.Timestamp)(nil),         // 21: google.protobuf.Timestamp
}
var file_flotestro_helper_v1_helper_proto_depIdxs = []int32{
	21, // 0: flotestro.helper.v1.HelperRequest.expires_at:type_name -> google.protobuf.Timestamp
	10, // 1: flotestro.helper.v1.HelperRequest.unit_action:type_name -> flotestro.helper.v1.UnitActionRequest
	9,  // 2: flotestro.helper.v1.HelperRequest.package_action:type_name -> flotestro.helper.v1.PackageActionRequest
	8,  // 3: flotestro.helper.v1.HelperRequest.reboot:type_name -> flotestro.helper.v1.RebootRequest
	7,  // 4: flotestro.helper.v1.HelperRequest.identity_probe:type_name -> flotestro.helper.v1.IdentityProbeRequest
	6,  // 5: flotestro.helper.v1.HelperRequest.domain_enroll:type_name -> flotestro.helper.v1.DomainEnrollRequest
	4,  // 6: flotestro.helper.v1.HelperRequest.local_accounts:type_name -> flotestro.helper.v1.LocalAccountsRequest
	5,  // 7: flotestro.helper.v1.HelperRequest.local_user_action:type_name -> flotestro.helper.v1.LocalUserActionRequest
	0,  // 8: flotestro.helper.v1.LocalUserActionRequest.operation:type_name -> flotestro.helper.v1.LocalUserActionRequest.Operation
	1,  // 9: flotestro.helper.v1.PackageActionRequest.operation:type_name -> flotestro.helper.v1.PackageActionRequest.Operation
	2,  // 10: flotestro.helper.v1.UnitActionRequest.operation:type_name -> flotestro.helper.v1.UnitActionRequest.Operation
	20, // 11: flotestro.helper.v1.HelperResponse.state_before:type_name -> flotestro.helper.v1.UnitState
	20, // 12: flotestro.helper.v1.HelperResponse.state_after:type_name -> flotestro.helper.v1.UnitState
	18, // 13: flotestro.helper.v1.HelperResponse.package_result:type_name -> flotestro.helper.v1.PackageActionResult
	17, // 14: flotestro.helper.v1.HelperResponse.identity_result:type_name -> flotestro.helper.v1.IdentityProbeResult
	15, // 15: flotestro.helper.v1.HelperResponse.enroll_result:type_name -> flotestro.helper.v1.DomainEnrollResult
	12, // 16: flotestro.helper.v1.HelperResponse.accounts_result:type_name -> flotestro.helper.v1.LocalAccountsResult
	13, // 17: flotestro.helper.v1.LocalAccountsResult.accounts:type_name -> flotestro.helper.v1.LocalAccountDetail
	14, // 18: flotestro.helper.v1.LocalAccountDetail.ssh_keys:type_name -> flotestro.helper.v1.LocalSSHKey
	16, // 19: flotestro.helper.v1.DomainEnrollResult.checks:type_name -> flotestro.helper.v1.EnrollCheck
	16, // 20: flotestro.helper.v1.DomainEnrollResult.verifications:type_name -> flotestro.helper.v1.EnrollCheck
	19, // 21: flotestro.helper.v1.PackageActionResult.applied:type_name -> flotestro.helper.v1.PackageVersionChange
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_flotestro_helper_v1_helper_proto_init() }
func file_flotestro_helper_v1_helper_proto_init() {
	if File_flotestro_helper_v1_helper_proto != nil {
		return
	}
	file_flotestro_helper_v1_helper_proto_msgTypes[0].OneofWrappers = []any{
		(*HelperRequest_UnitAction)(nil),
		(*HelperRequest_PackageAction)(nil),
		(*HelperRequest_Reboot)(nil),
		(*HelperRequest_IdentityProbe)(nil),
		(*HelperRequest_DomainEnroll)(nil),
		(*HelperRequest_LocalAccounts)(nil),
		(*HelperRequest_LocalUserAction)(nil),
	}
	file_flotestro_helper_v1_helper_proto_msgTypes[10].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[13].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flotestro_helper_v1_helper_proto_rawDesc), len(file_flotestro_helper_v1_helper_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flotestro_helper_v1_helper_proto_goTypes,
		DependencyIndexes: file_flotestro_helper_v1_helper_proto_depIdxs,
		EnumInfos:         file_flotestro_helper_v1_helper_proto_enumTypes,
		MessageInfos:      file_flotestro_helper_v1_helper_proto_msgTypes,
	}.Build()
	File_flotestro_helper_v1_helper_proto = out.File
	file_flotestro_helper_v1_helper_proto_goTypes = nil
	file_flotestro_helper_v1_helper_proto_depIdxs = nil
}
