// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: flotestro/helper/v1/helper.proto

package helperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalUserActionRequest_Operation int32

const (
	LocalUserActionRequest_OPERATION_UNSPECIFIED  LocalUserActionRequest_Operation = 0
	LocalUserActionRequest_OPERATION_CREATE       LocalUserActionRequest_Operation = 1
	LocalUserActionRequest_OPERATION_LOCK         LocalUserActionRequest_Operation = 2
	LocalUserActionRequest_OPERATION_UNLOCK       LocalUserActionRequest_Operation = 3
	LocalUserActionRequest_OPERATION_SET_SSH_KEYS LocalUserActionRequest_Operation = 4
)

// Enum value maps for LocalUserActionRequest_Operation.
var (
	LocalUserActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_LOCK",
		3: "OPERATION_UNLOCK",
		4: "OPERATION_SET_SSH_KEYS",
	}
	LocalUserActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":  0,
		"OPERATION_CREATE":       1,
		"OPERATION_LOCK":         2,
		"OPERATION_UNLOCK":       3,
		"OPERATION_SET_SSH_KEYS": 4,
	}
)

func (x LocalUserActionRequest_Operation) Enum() *LocalUserActionRequest_Operation {
	p := new(LocalUserActionRequest_Operation)
	*p = x
	return p
}

func (x LocalUserActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalUserActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[0].Descriptor()
}

func (LocalUserActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[0]
}

func (x LocalUserActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalUserActionRequest_Operation.Descriptor instead.
func (LocalUserActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{2, 0}
}

type PackageActionRequest_Operation int32

const (
	PackageActionRequest_OPERATION_UNSPECIFIED PackageActionRequest_Operation = 0
	// Odswiezenie metadanych repozytorium.
	PackageActionRequest_OPERATION_REFRESH PackageActionRequest_Operation = 1
	// Wykonanie transakcji aktualizacji.
	PackageActionRequest_OPERATION_UPGRADE PackageActionRequest_Operation = 2
)

// Enum value maps for PackageActionRequest_Operation.
var (
	PackageActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_REFRESH",
		2: "OPERATION_UPGRADE",
	}
	PackageActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_REFRESH":     1,
		"OPERATION_UPGRADE":     2,
	}
)

func (x PackageActionRequest_Operation) Enum() *PackageActionRequest_Operation {
	p := new(PackageActionRequest_Operation)
	*p = x
	return p
}

func (x PackageActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[1].Descriptor()
}

func (PackageActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[1]
}

func (x PackageActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageActionRequest_Operation.Descriptor instead.
func (PackageActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{6, 0}
}

type UnitActionRequest_Operation int32

const (
	UnitActionRequest_OPERATION_UNSPECIFIED UnitActionRequest_Operation = 0
	UnitActionRequest_OPERATION_START       UnitActionRequest_Operation = 1
	UnitActionRequest_OPERATION_STOP        UnitActionRequest_Operation = 2
	UnitActionRequest_OPERATION_RESTART     UnitActionRequest_Operation = 3
	UnitActionRequest_OPERATION_RELOAD      UnitActionRequest_Operation = 4
)

// Enum value maps for UnitActionRequest_Operation.
var (
	UnitActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_START",
		2: "OPERATION_STOP",
		3: "OPERATION_RESTART",
		4: "OPERATION_RELOAD",
	}
	UnitActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_START":       1,
		"OPERATION_STOP":        2,
		"OPERATION_RESTART":     3,
		"OPERATION_RELOAD":      4,
	}
)

func (x UnitActionRequest_Operation) Enum() *UnitActionRequest_Operation {
	p := new(UnitActionRequest_Operation)
	*p = x
	return p
}

func (x UnitActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[2].Descriptor()
}

func (UnitActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[2]
}

func (x UnitActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitActionRequest_Operation.Descriptor instead.
func (UnitActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{7, 0}
}

type DockerReadRequest_Scope int32

const (
	DockerReadRequest_SCOPE_UNSPECIFIED DockerReadRequest_Scope = 0
	// Podsumowanie do inventory: lekkie, liczone przy cyklu inwentarza.
	DockerReadRequest_SCOPE_SUMMARY DockerReadRequest_Scope = 1
	// Pelny stan na zadanie operatora, gdy otworzy zakladke.
	DockerReadRequest_SCOPE_FULL DockerReadRequest_Scope = 2
)

// Enum value maps for DockerReadRequest_Scope.
var (
	DockerReadRequest_Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_SUMMARY",
		2: "SCOPE_FULL",
	}
	DockerReadRequest_Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SCOPE_SUMMARY":     1,
		"SCOPE_FULL":        2,
	}
)

func (x DockerReadRequest_Scope) Enum() *DockerReadRequest_Scope {
	p := new(DockerReadRequest_Scope)
	*p = x
	return p
}

func (x DockerReadRequest_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DockerReadRequest_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[3].Descriptor()
}

func (DockerReadRequest_Scope) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[3]
}

func (x DockerReadRequest_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DockerReadRequest_Scope.Descriptor instead.
func (DockerReadRequest_Scope) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{9, 0}
}

type DockerActionRequest_Operation int32

const (
	DockerActionRequest_OPERATION_UNSPECIFIED DockerActionRequest_Operation = 0
	DockerActionRequest_OPERATION_START       DockerActionRequest_Operation = 1
	DockerActionRequest_OPERATION_STOP        DockerActionRequest_Operation = 2
	DockerActionRequest_OPERATION_RESTART     DockerActionRequest_Operation = 3
	DockerActionRequest_OPERATION_REMOVE      DockerActionRequest_Operation = 4
	DockerActionRequest_OPERATION_PULL_IMAGE  DockerActionRequest_Operation = 5
	DockerActionRequest_OPERATION_PRUNE       DockerActionRequest_Operation = 6
)

// Enum value maps for DockerActionRequest_Operation.
var (
	DockerActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_START",
		2: "OPERATION_STOP",
		3: "OPERATION_RESTART",
		4: "OPERATION_REMOVE",
		5: "OPERATION_PULL_IMAGE",
		6: "OPERATION_PRUNE",
	}
	DockerActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_START":       1,
		"OPERATION_STOP":        2,
		"OPERATION_RESTART":     3,
		"OPERATION_REMOVE":      4,
		"OPERATION_PULL_IMAGE":  5,
		"OPERATION_PRUNE":       6,
	}
)

func (x DockerActionRequest_Operation) Enum() *DockerActionRequest_Operation {
	p := new(DockerActionRequest_Operation)
	*p = x
	return p
}

func (x DockerActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DockerActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[4].Descriptor()
}

func (DockerActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[4]
}

func (x DockerActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DockerActionRequest_Operation.Descriptor instead.
func (DockerActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{10, 0}
}

// PROTOCOL_VERSION zmienia sie przy kazdej niezgodnej zmianie kontraktu.
// Helper odrzuca wersje, ktorej nie zna, zamiast zgadywac znaczenie pol.
type HelperRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Helper odrzuca zadanie po terminie, niezaleznie od tego, co twierdzi agent.
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxOutputBytes uint32                 `protobuf:"varint,5,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*HelperRequest_UnitAction
	//	*HelperRequest_PackageAction
	//	*HelperRequest_Reboot
	//	*HelperRequest_IdentityProbe
	//	*HelperRequest_DomainEnroll
	//	*HelperRequest_LocalAccounts
	//	*HelperRequest_LocalUserAction
	//	*HelperRequest_PackageRepair
	//	*HelperRequest_DockerRead
	//	*HelperRequest_DockerAction
	Action isHelperRequest_Action `protobuf_oneof:"action"`
	// Postep dlugiej operacji. Klient, ktory o niego nie prosi, dostaje jedna
	// odpowiedz jak dotad - starszy agent nie moze wziac wiadomosci o postepie
	// za wynik operacji.
	WantProgress  bool `protobuf:"varint,28,opt,name=want_progress,json=wantProgress,proto3" json:"want_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperRequest) Reset() {
	*x = HelperRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperRequest) ProtoMessage() {}

func (x *HelperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperRequest.ProtoReflect.Descriptor instead.
func (*HelperRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{0}
}

func (x *HelperRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelperRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HelperRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *HelperRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HelperRequest) GetMaxOutputBytes() uint32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *HelperRequest) GetAction() isHelperRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *HelperRequest) GetUnitAction() *UnitActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_UnitAction); ok {
			return x.UnitAction
		}
	}
	return nil
}

func (x *HelperRequest) GetPackageAction() *PackageActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_PackageAction); ok {
			return x.PackageAction
		}
	}
	return nil
}

func (x *HelperRequest) GetReboot() *RebootRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *HelperRequest) GetIdentityProbe() *IdentityProbeRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_IdentityProbe); ok {
			return x.IdentityProbe
		}
	}
	return nil
}

func (x *HelperRequest) GetDomainEnroll() *DomainEnrollRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_DomainEnroll); ok {
			return x.DomainEnroll
		}
	}
	return nil
}

func (x *HelperRequest) GetLocalAccounts() *LocalAccountsRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_LocalAccounts); ok {
			return x.LocalAccounts
		}
	}
	return nil
}

func (x *HelperRequest) GetLocalUserAction() *LocalUserActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_LocalUserAction); ok {
			return x.LocalUserAction
		}
	}
	return nil
}

func (x *HelperRequest) GetPackageRepair() *PackageRepairRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_PackageRepair); ok {
			return x.PackageRepair
		}
	}
	return nil
}

func (x *HelperRequest) GetDockerRead() *DockerReadRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_DockerRead); ok {
			return x.DockerRead
		}
	}
	return nil
}

func (x *HelperRequest) GetDockerAction() *DockerActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_DockerAction); ok {
			return x.DockerAction
		}
	}
	return nil
}

func (x *HelperRequest) GetWantProgress() bool {
	if x != nil {
		return x.WantProgress
	}
	return false
}

type isHelperRequest_Action interface {
	isHelperRequest_Action()
}

type HelperRequest_UnitAction struct {
	UnitAction *UnitActionRequest `protobuf:"bytes,20,opt,name=unit_action,json=unitAction,proto3,oneof"`
}

type HelperRequest_PackageAction struct {
	PackageAction *PackageActionRequest `protobuf:"bytes,21,opt,name=package_action,json=packageAction,proto3,oneof"`
}

type HelperRequest_Reboot struct {
	Reboot *RebootRequest `protobuf:"bytes,22,opt,name=reboot,proto3,oneof"`
}

type HelperRequest_IdentityProbe struct {
	IdentityProbe *IdentityProbeRequest `protobuf:"bytes,23,opt,name=identity_probe,json=identityProbe,proto3,oneof"`
}

type HelperRequest_DomainEnroll struct {
	DomainEnroll *DomainEnrollRequest `protobuf:"bytes,24,opt,name=domain_enroll,json=domainEnroll,proto3,oneof"`
}

type HelperRequest_LocalAccounts struct {
	LocalAccounts *LocalAccountsRequest `protobuf:"bytes,25,opt,name=local_accounts,json=localAccounts,proto3,oneof"`
}

type HelperRequest_LocalUserAction struct {
	LocalUserAction *LocalUserActionRequest `protobuf:"bytes,26,opt,name=local_user_action,json=localUserAction,proto3,oneof"`
}

type HelperRequest_PackageRepair struct {
	PackageRepair *PackageRepairRequest `protobuf:"bytes,27,opt,name=package_repair,json=packageRepair,proto3,oneof"`
}

type HelperRequest_DockerRead struct {
	// Odczyt stanu silnika kontenerow. Agent nie dostaje gniazda Dockera:
	// czlonkostwo w grupie docker jest rownowazne rootowi, wiec proces
	// dzialajacy bez uprawnien nie moze go miec.
	DockerRead *DockerReadRequest `protobuf:"bytes,29,opt,name=docker_read,json=dockerRead,proto3,oneof"`
}

type HelperRequest_DockerAction struct {
	// Operacja na silniku kontenerow. Zakres jest wyliczony, a nie podany
	// sciezka: helper nie posredniczy w dowolnym wywolaniu Engine API.
	DockerAction *DockerActionRequest `protobuf:"bytes,30,opt,name=docker_action,json=dockerAction,proto3,oneof"`
}

func (*HelperRequest_UnitAction) isHelperRequest_Action() {}

func (*HelperRequest_PackageAction) isHelperRequest_Action() {}

func (*HelperRequest_Reboot) isHelperRequest_Action() {}

func (*HelperRequest_IdentityProbe) isHelperRequest_Action() {}

func (*HelperRequest_DomainEnroll) isHelperRequest_Action() {}

func (*HelperRequest_LocalAccounts) isHelperRequest_Action() {}

func (*HelperRequest_LocalUserAction) isHelperRequest_Action() {}

func (*HelperRequest_PackageRepair) isHelperRequest_Action() {}

func (*HelperRequest_DockerRead) isHelperRequest_Action() {}

func (*HelperRequest_DockerAction) isHelperRequest_Action() {}

// LocalAccountsRequest odczytuje te dane o kontach, ktore wymagaja roota:
// stan blokady z /etc/shadow i klucze SSH z katalogow domowych.
type LocalAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalAccountsRequest) Reset() {
	*x = LocalAccountsRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAccountsRequest) ProtoMessage() {}

func (x *LocalAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAccountsRequest.ProtoReflect.Descriptor instead.
func (*LocalAccountsRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{1}
}

func (x *LocalAccountsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// LocalUserActionRequest zmienia konto lokalne na hoscie.
type LocalUserActionRequest struct {
	state     protoimpl.MessageState           `protogen:"open.v1"`
	Operation LocalUserActionRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=flotestro.helper.v1.LocalUserActionRequest_Operation" json:"operation,omitempty"`
	Name      string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gecos     string                           `protobuf:"bytes,3,opt,name=gecos,proto3" json:"gecos,omitempty"`
	Shell     string                           `protobuf:"bytes,4,opt,name=shell,proto3" json:"shell,omitempty"`
	Groups    []string                         `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	// Klucze publiczne w postaci pelnej. Klucz prywatny nigdy nie trafia
	// do systemu, a hasla nie sa przesylane w ogole.
	SshKeys []string `protobuf:"bytes,6,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	// CreateHome tworzy katalog domowy przy zakladaniu konta.
	CreateHome    bool `protobuf:"varint,7,opt,name=create_home,json=createHome,proto3" json:"create_home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalUserActionRequest) Reset() {
	*x = LocalUserActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalUserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUserActionRequest) ProtoMessage() {}

func (x *LocalUserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUserActionRequest.ProtoReflect.Descriptor instead.
func (*LocalUserActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{2}
}

func (x *LocalUserActionRequest) GetOperation() LocalUserActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return LocalUserActionRequest_OPERATION_UNSPECIFIED
}

func (x *LocalUserActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalUserActionRequest) GetGecos() string {
	if x != nil {
		return x.Gecos
	}
	return ""
}

func (x *LocalUserActionRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *LocalUserActionRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *LocalUserActionRequest) GetSshKeys() []string {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

func (x *LocalUserActionRequest) GetCreateHome() bool {
	if x != nil {
		return x.CreateHome
	}
	return false
}

// DomainEnrollRequest dolacza hosta do domeny. Wymaga roota, bo zmienia
// konfiguracje SSSD, Kerberosa i PAM.
type DomainEnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Domain          string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Realm           string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Server          string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	OneTimePassword string                 `protobuf:"bytes,4,opt,name=one_time_password,json=oneTimePassword,proto3" json:"one_time_password,omitempty"`
	Hostname        string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PreflightOnly   bool                   `protobuf:"varint,6,opt,name=preflight_only,json=preflightOnly,proto3" json:"preflight_only,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DomainEnrollRequest) Reset() {
	*x = DomainEnrollRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEnrollRequest) ProtoMessage() {}

func (x *DomainEnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEnrollRequest.ProtoReflect.Descriptor instead.
func (*DomainEnrollRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{3}
}

func (x *DomainEnrollRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainEnrollRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *DomainEnrollRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *DomainEnrollRequest) GetOneTimePassword() string {
	if x != nil {
		return x.OneTimePassword
	}
	return ""
}

func (x *DomainEnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DomainEnrollRequest) GetPreflightOnly() bool {
	if x != nil {
		return x.PreflightOnly
	}
	return false
}

// IdentityProbeRequest odczytuje te elementy stanu domeny, ktore wymagaja
// roota: keytab hosta i baze cache SSSD. Reszte agent czyta sam.
type IdentityProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityProbeRequest) Reset() {
	*x = IdentityProbeRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProbeRequest) ProtoMessage() {}

func (x *IdentityProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProbeRequest.ProtoReflect.Descriptor instead.
func (*IdentityProbeRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityProbeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// RebootRequest zleca kontrolowany restart hosta.
type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{5}
}

func (x *RebootRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *RebootRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PackageActionRequest obejmuje operacje pakietowe wymagajace roota.
// Planowanie w trybie symulacji nie wymaga roota i nie idzie przez helper.
type PackageActionRequest struct {
	state     protoimpl.MessageState         `protogen:"open.v1"`
	Operation PackageActionRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=flotestro.helper.v1.PackageActionRequest_Operation" json:"operation,omitempty"`
	// Pusta lista przy OPERATION_UPGRADE oznacza wszystkie aktualizacje.
	Packages      []string `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	SecurityOnly  bool     `protobuf:"varint,3,opt,name=security_only,json=securityOnly,proto3" json:"security_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageActionRequest) Reset() {
	*x = PackageActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageActionRequest) ProtoMessage() {}

func (x *PackageActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageActionRequest.ProtoReflect.Descriptor instead.
func (*PackageActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{6}
}

func (x *PackageActionRequest) GetOperation() PackageActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return PackageActionRequest_OPERATION_UNSPECIFIED
}

func (x *PackageActionRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackageActionRequest) GetSecurityOnly() bool {
	if x != nil {
		return x.SecurityOnly
	}
	return false
}

type UnitActionRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Unit          string                      `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Operation     UnitActionRequest_Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=flotestro.helper.v1.UnitActionRequest_Operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitActionRequest) Reset() {
	*x = UnitActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitActionRequest) ProtoMessage() {}

func (x *UnitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitActionRequest.ProtoReflect.Descriptor instead.
func (*UnitActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{7}
}

func (x *UnitActionRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitActionRequest) GetOperation() UnitActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return UnitActionRequest_OPERATION_UNSPECIFIED
}

type HelperResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Stabilny kod maszynowy: unknown_action, unsupported_version, expired,
	// protected_unit, invalid_unit, locked, exec_failed, timeout.
	ErrorCode       string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode        int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          []byte                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          []byte                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	OutputTruncated bool                   `protobuf:"varint,7,opt,name=output_truncated,json=outputTruncated,proto3" json:"output_truncated,omitempty"`
	StateBefore     *UnitState             `protobuf:"bytes,8,opt,name=state_before,json=stateBefore,proto3" json:"state_before,omitempty"`
	StateAfter      *UnitState             `protobuf:"bytes,9,opt,name=state_after,json=stateAfter,proto3" json:"state_after,omitempty"`
	PackageResult   *PackageActionResult   `protobuf:"bytes,10,opt,name=package_result,json=packageResult,proto3" json:"package_result,omitempty"`
	IdentityResult  *IdentityProbeResult   `protobuf:"bytes,11,opt,name=identity_result,json=identityResult,proto3" json:"identity_result,omitempty"`
	EnrollResult    *DomainEnrollResult    `protobuf:"bytes,12,opt,name=enroll_result,json=enrollResult,proto3" json:"enroll_result,omitempty"`
	AccountsResult  *LocalAccountsResult   `protobuf:"bytes,13,opt,name=accounts_result,json=accountsResult,proto3" json:"accounts_result,omitempty"`
	RepairResult    *PackageRepairResponse `protobuf:"bytes,14,opt,name=repair_result,json=repairResult,proto3" json:"repair_result,omitempty"`
	// Postep operacji w toku. Wiadomosc z postepem nie jest odpowiedzia
	// koncowa: klient czyta dalej, az dostanie final = true.
	Progress           *TaskProgress       `protobuf:"bytes,15,opt,name=progress,proto3" json:"progress,omitempty"`
	Final              bool                `protobuf:"varint,16,opt,name=final,proto3" json:"final,omitempty"`
	DockerResult       *DockerReadResult   `protobuf:"bytes,17,opt,name=docker_result,json=dockerResult,proto3" json:"docker_result,omitempty"`
	DockerActionResult *DockerActionResult `protobuf:"bytes,18,opt,name=docker_action_result,json=dockerActionResult,proto3" json:"docker_action_result,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelperResponse) Reset() {
	*x = HelperResponse{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperResponse) ProtoMessage() {}

func (x *HelperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperResponse.ProtoReflect.Descriptor instead.
func (*HelperResponse) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{8}
}

func (x *HelperResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelperResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *HelperResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelperResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *HelperResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *HelperResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *HelperResponse) GetOutputTruncated() bool {
	if x != nil {
		return x.OutputTruncated
	}
	return false
}

func (x *HelperResponse) GetStateBefore() *UnitState {
	if x != nil {
		return x.StateBefore
	}
	return nil
}

func (x *HelperResponse) GetStateAfter() *UnitState {
	if x != nil {
		return x.StateAfter
	}
	return nil
}

func (x *HelperResponse) GetPackageResult() *PackageActionResult {
	if x != nil {
		return x.PackageResult
	}
	return nil
}

func (x *HelperResponse) GetIdentityResult() *IdentityProbeResult {
	if x != nil {
		return x.IdentityResult
	}
	return nil
}

func (x *HelperResponse) GetEnrollResult() *DomainEnrollResult {
	if x != nil {
		return x.EnrollResult
	}
	return nil
}

func (x *HelperResponse) GetAccountsResult() *LocalAccountsResult {
	if x != nil {
		return x.AccountsResult
	}
	return nil
}

func (x *HelperResponse) GetRepairResult() *PackageRepairResponse {
	if x != nil {
		return x.RepairResult
	}
	return nil
}

func (x *HelperResponse) GetProgress() *TaskProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *HelperResponse) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *HelperResponse) GetDockerResult() *DockerReadResult {
	if x != nil {
		return x.DockerResult
	}
	return nil
}

func (x *HelperResponse) GetDockerActionResult() *DockerActionResult {
	if x != nil {
		return x.DockerActionResult
	}
	return nil
}

// DockerReadRequest opisuje, co odczytac z silnika. Zakres jest wyliczony,
// a nie podany sciezka: przekazanie sciezki do Engine API oznaczaloby, ze
// przez helpera da sie wywolac dowolna jego operacje.
type DockerReadRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Scope         DockerReadRequest_Scope `protobuf:"varint,1,opt,name=scope,proto3,enum=flotestro.helper.v1.DockerReadRequest_Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerReadRequest) Reset() {
	*x = DockerReadRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerReadRequest) ProtoMessage() {}

func (x *DockerReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerReadRequest.ProtoReflect.Descriptor instead.
func (*DockerReadRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{9}
}

func (x *DockerReadRequest) GetScope() DockerReadRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return DockerReadRequest_SCOPE_UNSPECIFIED
}

// DockerActionRequest opisuje jedna operacje na silniku.
type DockerActionRequest struct {
	state     protoimpl.MessageState        `protogen:"open.v1"`
	Operation DockerActionRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=flotestro.helper.v1.DockerActionRequest_Operation" json:"operation,omitempty"`
	// Identyfikator kontenera; wylacznie szesnastkowy, sprawdzony przed
	// wyslaniem i sprawdzony ponownie tutaj.
	ContainerId    string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	TimeoutSeconds uint32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RemoveVolumes  bool   `protobuf:"varint,4,opt,name=remove_volumes,json=removeVolumes,proto3" json:"remove_volumes,omitempty"`
	ImageReference string `protobuf:"bytes,5,opt,name=image_reference,json=imageReference,proto3" json:"image_reference,omitempty"`
	// Obiekty do usuniecia przy sprzataniu. Lista jest jawna: sprzatanie po
	// filtrze usunęłoby takze to, czego operator nie widzial.
	ImageIds      []string `protobuf:"bytes,6,rep,name=image_ids,json=imageIds,proto3" json:"image_ids,omitempty"`
	VolumeNames   []string `protobuf:"bytes,7,rep,name=volume_names,json=volumeNames,proto3" json:"volume_names,omitempty"`
	NetworkIds    []string `protobuf:"bytes,8,rep,name=network_ids,json=networkIds,proto3" json:"network_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerActionRequest) Reset() {
	*x = DockerActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerActionRequest) ProtoMessage() {}

func (x *DockerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerActionRequest.ProtoReflect.Descriptor instead.
func (*DockerActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{10}
}

func (x *DockerActionRequest) GetOperation() DockerActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return DockerActionRequest_OPERATION_UNSPECIFIED
}

func (x *DockerActionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DockerActionRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DockerActionRequest) GetRemoveVolumes() bool {
	if x != nil {
		return x.RemoveVolumes
	}
	return false
}

func (x *DockerActionRequest) GetImageReference() string {
	if x != nil {
		return x.ImageReference
	}
	return ""
}

func (x *DockerActionRequest) GetImageIds() []string {
	if x != nil {
		return x.ImageIds
	}
	return nil
}

func (x *DockerActionRequest) GetVolumeNames() []string {
	if x != nil {
		return x.VolumeNames
	}
	return nil
}

func (x *DockerActionRequest) GetNetworkIds() []string {
	if x != nil {
		return x.NetworkIds
	}
	return nil
}

type DockerActionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stan kontenera przed i po, w postaci JSON. Zapisywany takze przy bledzie:
	// bez tego nie wiadomo, co zdazylo sie zmienic.
	Before         []byte   `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After          []byte   `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Removed        []string `protobuf:"bytes,3,rep,name=removed,proto3" json:"removed,omitempty"`
	ReclaimedBytes *int64   `protobuf:"varint,4,opt,name=reclaimed_bytes,json=reclaimedBytes,proto3,oneof" json:"reclaimed_bytes,omitempty"`
	ImageDigest    string   `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DockerActionResult) Reset() {
	*x = DockerActionResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerActionResult) ProtoMessage() {}

func (x *DockerActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerActionResult.ProtoReflect.Descriptor instead.
func (*DockerActionResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{11}
}

func (x *DockerActionResult) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *DockerActionResult) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *DockerActionResult) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *DockerActionResult) GetReclaimedBytes() int64 {
	if x != nil && x.ReclaimedBytes != nil {
		return *x.ReclaimedBytes
	}
	return 0
}

func (x *DockerActionResult) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

type DockerReadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stan silnika w postaci JSON. Struktura nalezy do modulu kontenerow
	// i nie jest powtarzana w kontrakcie helpera - helper jej nie interpretuje,
	// tylko przenosi.
	Snapshot []byte `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// Powod, dla ktorego stanu nie udalo sie ustalic. Pusty silnik i silnik
	// nieodpytany to dwie rozne informacje.
	UnavailableReason string `protobuf:"bytes,2,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DockerReadResult) Reset() {
	*x = DockerReadResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerReadResult) ProtoMessage() {}

func (x *DockerReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerReadResult.ProtoReflect.Descriptor instead.
func (*DockerReadResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{12}
}

func (x *DockerReadResult) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *DockerReadResult) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

// TaskProgress opisuje postep operacji, ktora trwa na tyle dlugo, ze operator
// musi widziec, na czym stoi. Postep jest ulotny: nie zastepuje wyniku i nie
// jest zapisywany - liczy sie to, co widac teraz.
type TaskProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Krok i liczba krokow, gdy narzedzie je podaje. Zero oznacza nieznane
	// i nie moze byc pokazane jako zero krokow.
	Step  uint32 `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Total uint32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Procent podawany osobno, bo apt zna procent bez krokow, a dnf kroki
	// bez procentu. Brak pola oznacza postep nieustalony.
	Percent *uint32 `protobuf:"varint,3,opt,name=percent,proto3,oneof" json:"percent,omitempty"`
	// Co sie akurat dzieje, np. "Upgrading nfs-utils".
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{13}
}

func (x *TaskProgress) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *TaskProgress) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskProgress) GetPercent() uint32 {
	if x != nil && x.Percent != nil {
		return *x.Percent
	}
	return 0
}

func (x *TaskProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LocalAccountsResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accounts          []*LocalAccountDetail  `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	UnavailableReason string                 `protobuf:"bytes,2,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocalAccountsResult) Reset() {
	*x = LocalAccountsResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAccountsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAccountsResult) ProtoMessage() {}

func (x *LocalAccountsResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAccountsResult.ProtoReflect.Descriptor instead.
func (*LocalAccountsResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{14}
}

func (x *LocalAccountsResult) GetAccounts() []*LocalAccountDetail {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *LocalAccountsResult) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type LocalAccountDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Locked        *bool                  `protobuf:"varint,2,opt,name=locked,proto3,oneof" json:"locked,omitempty"`
	SshKeys       []*LocalSSHKey         `protobuf:"bytes,3,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	PasswordSet   *bool                  `protobuf:"varint,4,opt,name=password_set,json=passwordSet,proto3,oneof" json:"password_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalAccountDetail) Reset() {
	*x = LocalAccountDetail{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAccountDetail) ProtoMessage() {}

func (x *LocalAccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAccountDetail.ProtoReflect.Descriptor instead.
func (*LocalAccountDetail) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{15}
}

func (x *LocalAccountDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalAccountDetail) GetLocked() bool {
	if x != nil && x.Locked != nil {
		return *x.Locked
	}
	return false
}

func (x *LocalAccountDetail) GetSshKeys() []*LocalSSHKey {
	if x != nil {
		return x.SshKeys
	}
	return nil
}

func (x *LocalAccountDetail) GetPasswordSet() bool {
	if x != nil && x.PasswordSet != nil {
		return *x.PasswordSet
	}
	return false
}

type LocalSSHKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalSSHKey) Reset() {
	*x = LocalSSHKey{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSSHKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSSHKey) ProtoMessage() {}

func (x *LocalSSHKey) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSSHKey.ProtoReflect.Descriptor instead.
func (*LocalSSHKey) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{16}
}

func (x *LocalSSHKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *LocalSSHKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LocalSSHKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DomainEnrollResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*EnrollCheck         `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	Enrolled      bool                   `protobuf:"varint,2,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	HostPrincipal string                 `protobuf:"bytes,3,opt,name=host_principal,json=hostPrincipal,proto3" json:"host_principal,omitempty"`
	Verifications []*EnrollCheck         `protobuf:"bytes,4,rep,name=verifications,proto3" json:"verifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEnrollResult) Reset() {
	*x = DomainEnrollResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEnrollResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEnrollResult) ProtoMessage() {}

func (x *DomainEnrollResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEnrollResult.ProtoReflect.Descriptor instead.
func (*DomainEnrollResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{17}
}

func (x *DomainEnrollResult) GetChecks() []*EnrollCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *DomainEnrollResult) GetEnrolled() bool {
	if x != nil {
		return x.Enrolled
	}
	return false
}

func (x *DomainEnrollResult) GetHostPrincipal() string {
	if x != nil {
		return x.HostPrincipal
	}
	return ""
}

func (x *DomainEnrollResult) GetVerifications() []*EnrollCheck {
	if x != nil {
		return x.Verifications
	}
	return nil
}

type EnrollCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passed        *bool                  `protobuf:"varint,2,opt,name=passed,proto3,oneof" json:"passed,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Blocking      bool                   `protobuf:"varint,4,opt,name=blocking,proto3" json:"blocking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollCheck) Reset() {
	*x = EnrollCheck{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCheck) ProtoMessage() {}

func (x *EnrollCheck) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCheck.ProtoReflect.Descriptor instead.
func (*EnrollCheck) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{18}
}

func (x *EnrollCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollCheck) GetPassed() bool {
	if x != nil && x.Passed != nil {
		return *x.Passed
	}
	return false
}

func (x *EnrollCheck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *EnrollCheck) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

type IdentityProbeResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostPrincipal   string                 `protobuf:"bytes,1,opt,name=host_principal,json=hostPrincipal,proto3" json:"host_principal,omitempty"`
	KeytabKvno      *uint32                `protobuf:"varint,2,opt,name=keytab_kvno,json=keytabKvno,proto3,oneof" json:"keytab_kvno,omitempty"`
	CacheAgeSeconds *uint64                `protobuf:"varint,3,opt,name=cache_age_seconds,json=cacheAgeSeconds,proto3,oneof" json:"cache_age_seconds,omitempty"`
	SssdOnline      *bool                  `protobuf:"varint,4,opt,name=sssd_online,json=sssdOnline,proto3,oneof" json:"sssd_online,omitempty"`
	ConfigIssues    []string               `protobuf:"bytes,5,rep,name=config_issues,json=configIssues,proto3" json:"config_issues,omitempty"`
	// Powod, dla ktorego czesci stanu nie udalo sie ustalic.
	UnavailableReason string `protobuf:"bytes,6,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IdentityProbeResult) Reset() {
	*x = IdentityProbeResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProbeResult) ProtoMessage() {}

func (x *IdentityProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProbeResult.ProtoReflect.Descriptor instead.
func (*IdentityProbeResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{19}
}

func (x *IdentityProbeResult) GetHostPrincipal() string {
	if x != nil {
		return x.HostPrincipal
	}
	return ""
}

func (x *IdentityProbeResult) GetKeytabKvno() uint32 {
	if x != nil && x.KeytabKvno != nil {
		return *x.KeytabKvno
	}
	return 0
}

func (x *IdentityProbeResult) GetCacheAgeSeconds() uint64 {
	if x != nil && x.CacheAgeSeconds != nil {
		return *x.CacheAgeSeconds
	}
	return 0
}

func (x *IdentityProbeResult) GetSssdOnline() bool {
	if x != nil && x.SssdOnline != nil {
		return *x.SssdOnline
	}
	return false
}

func (x *IdentityProbeResult) GetConfigIssues() []string {
	if x != nil {
		return x.ConfigIssues
	}
	return nil
}

func (x *IdentityProbeResult) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type PackageActionResult struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Manager                string                  `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	Applied                []*PackageVersionChange `protobuf:"bytes,2,rep,name=applied,proto3" json:"applied,omitempty"`
	RebootRequired         bool                    `protobuf:"varint,3,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	ServicesNeedingRestart []string                `protobuf:"bytes,4,rep,name=services_needing_restart,json=servicesNeedingRestart,proto3" json:"services_needing_restart,omitempty"`
	// Prawda, gdy baza pakietow wymaga naprawy po nieudanej transakcji.
	PackageDatabaseBroken bool `protobuf:"varint,5,opt,name=package_database_broken,json=packageDatabaseBroken,proto3" json:"package_database_broken,omitempty"`
	// Pakiety, ktore czekaja na dokonczenie konfiguracji albo sa uszkodzone.
	PackagesNeedingAttention []string `protobuf:"bytes,6,rep,name=packages_needing_attention,json=packagesNeedingAttention,proto3" json:"packages_needing_attention,omitempty"`
	// Co adapter naprawil sam przed ponowieniem transakcji. Cicha naprawa
	// bylaby gorsza od jej braku: host zostal dotkniety inaczej, niz zlecono.
	SelfRepair []string `protobuf:"bytes,7,rep,name=self_repair,json=selfRepair,proto3" json:"self_repair,omitempty"`
	// Koncowka wyjscia narzedzia przy niepowodzeniu.
	Output        []string `protobuf:"bytes,8,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageActionResult) Reset() {
	*x = PackageActionResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageActionResult) ProtoMessage() {}

func (x *PackageActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageActionResult.ProtoReflect.Descriptor instead.
func (*PackageActionResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{20}
}

func (x *PackageActionResult) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *PackageActionResult) GetApplied() []*PackageVersionChange {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *PackageActionResult) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *PackageActionResult) GetServicesNeedingRestart() []string {
	if x != nil {
		return x.ServicesNeedingRestart
	}
	return nil
}

func (x *PackageActionResult) GetPackageDatabaseBroken() bool {
	if x != nil {
		return x.PackageDatabaseBroken
	}
	return false
}

func (x *PackageActionResult) GetPackagesNeedingAttention() []string {
	if x != nil {
		return x.PackagesNeedingAttention
	}
	return nil
}

func (x *PackageActionResult) GetSelfRepair() []string {
	if x != nil {
		return x.SelfRepair
	}
	return nil
}

func (x *PackageActionResult) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

// PackageRepairRequest odblokowuje operacje pakietowe. Odpowiedzi na pytania
// konfiguracyjne pochodza od operatora i sa ustawiane przed dokonczeniem
// konfiguracji pakietow.
type PackageRepairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*DebconfSelection    `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageRepairRequest) Reset() {
	*x = PackageRepairRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRepairRequest) ProtoMessage() {}

func (x *PackageRepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRepairRequest.ProtoReflect.Descriptor instead.
func (*PackageRepairRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{21}
}

func (x *PackageRepairRequest) GetAnswers() []*DebconfSelection {
	if x != nil {
		return x.Answers
	}
	return nil
}

type DebconfSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebconfSelection) Reset() {
	*x = DebconfSelection{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebconfSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebconfSelection) ProtoMessage() {}

func (x *DebconfSelection) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebconfSelection.ProtoReflect.Descriptor instead.
func (*DebconfSelection) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{22}
}

func (x *DebconfSelection) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *DebconfSelection) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *DebconfSelection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DebconfSelection) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PackageRepairResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Manager       string                  `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	StillBlocked  []*BlockedPackageDetail `protobuf:"bytes,2,rep,name=still_blocked,json=stillBlocked,proto3" json:"still_blocked,omitempty"`
	Answered      []string                `protobuf:"bytes,3,rep,name=answered,proto3" json:"answered,omitempty"`
	Repaired      bool                    `protobuf:"varint,4,opt,name=repaired,proto3" json:"repaired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageRepairResponse) Reset() {
	*x = PackageRepairResponse{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRepairResponse) ProtoMessage() {}

func (x *PackageRepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRepairResponse.ProtoReflect.Descriptor instead.
func (*PackageRepairResponse) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{23}
}

func (x *PackageRepairResponse) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *PackageRepairResponse) GetStillBlocked() []*BlockedPackageDetail {
	if x != nil {
		return x.StillBlocked
	}
	return nil
}

func (x *PackageRepairResponse) GetAnswered() []string {
	if x != nil {
		return x.Answered
	}
	return nil
}

func (x *PackageRepairResponse) GetRepaired() bool {
	if x != nil {
		return x.Repaired
	}
	return false
}

type BlockedPackageDetail struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Questions     []*DebconfQuestionDetail `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedPackageDetail) Reset() {
	*x = BlockedPackageDetail{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedPackageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedPackageDetail) ProtoMessage() {}

func (x *BlockedPackageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedPackageDetail.ProtoReflect.Descriptor instead.
func (*BlockedPackageDetail) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{24}
}

func (x *BlockedPackageDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlockedPackageDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BlockedPackageDetail) GetQuestions() []*DebconfQuestionDetail {
	if x != nil {
		return x.Questions
	}
	return nil
}

type DebconfQuestionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Answered      *bool                  `protobuf:"varint,3,opt,name=answered,proto3,oneof" json:"answered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebconfQuestionDetail) Reset() {
	*x = DebconfQuestionDetail{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebconfQuestionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebconfQuestionDetail) ProtoMessage() {}

func (x *DebconfQuestionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebconfQuestionDetail.ProtoReflect.Descriptor instead.
func (*DebconfQuestionDetail) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{25}
}

func (x *DebconfQuestionDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DebconfQuestionDetail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DebconfQuestionDetail) GetAnswered() bool {
	if x != nil && x.Answered != nil {
		return *x.Answered
	}
	return false
}

type PackageVersionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionBefore string                 `protobuf:"bytes,2,opt,name=version_before,json=versionBefore,proto3" json:"version_before,omitempty"`
	VersionAfter  string                 `protobuf:"bytes,3,opt,name=version_after,json=versionAfter,proto3" json:"version_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageVersionChange) Reset() {
	*x = PackageVersionChange{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageVersionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageVersionChange) ProtoMessage() {}

func (x *PackageVersionChange) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageVersionChange.ProtoReflect.Descriptor instead.
func (*PackageVersionChange) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{26}
}

func (x *PackageVersionChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageVersionChange) GetVersionBefore() string {
	if x != nil {
		return x.VersionBefore
	}
	return ""
}

func (x *PackageVersionChange) GetVersionAfter() string {
	if x != nil {
		return x.VersionAfter
	}
	return ""
}

type UnitState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LoadState     string                 `protobuf:"bytes,2,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	ActiveState   string                 `protobuf:"bytes,3,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	SubState      string                 `protobuf:"bytes,4,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`
	UnitFileState string                 `protobuf:"bytes,5,opt,name=unit_file_state,json=unitFileState,proto3" json:"unit_file_state,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	MainPid       uint32                 `protobuf:"varint,7,opt,name=main_pid,json=mainPid,proto3" json:"main_pid,omitempty"`
	NRestarts     uint32                 `protobuf:"varint,8,opt,name=n_restarts,json=nRestarts,proto3" json:"n_restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitState) Reset() {
	*x = UnitState{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitState) ProtoMessage() {}

func (x *UnitState) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitState.ProtoReflect.Descriptor instead.
func (*UnitState) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{27}
}

func (x *UnitState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitState) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *UnitState) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *UnitState) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *UnitState) GetUnitFileState() string {
	if x != nil {
		return x.UnitFileState
	}
	return ""
}

func (x *UnitState) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *UnitState) GetMainPid() uint32 {
	if x != nil {
		return x.MainPid
	}
	return 0
}

func (x *UnitState) GetNRestarts() uint32 {
	if x != nil {
		return x.NRestarts
	}
	return 0
}

var File_flotestro_helper_v1_helper_proto protoreflect.FileDescriptor

const file_flotestro_helper_v1_helper_proto_rawDesc = "" +
	"\n" +
	" flotestro/helper/v1/helper.proto\x12\x13flotestro.helper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\b\n" +
	"\rHelperRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12(\n" +
	"\x10max_output_bytes\x18\x05 \x01(\rR\x0emaxOutputBytes\x12I\n" +
	"\vunit_action\x18\x14 \x01(\v2&.flotestro.helper.v1.UnitActionRequestH\x00R\n" +
	"unitAction\x12R\n" +
	"\x0epackage_action\x18\x15 \x01(\v2).flotestro.helper.v1.PackageActionRequestH\x00R\rpackageAction\x12<\n" +
	"\x06reboot\x18\x16 \x01(\v2\".flotestro.helper.v1.RebootRequestH\x00R\x06reboot\x12R\n" +
	"\x0eidentity_probe\x18\x17 \x01(\v2).flotestro.helper.v1.IdentityProbeRequestH\x00R\ridentityProbe\x12O\n" +
	"\rdomain_enroll\x18\x18 \x01(\v2(.flotestro.helper.v1.DomainEnrollRequestH\x00R\fdomainEnroll\x12R\n" +
	"\x0elocal_accounts\x18\x19 \x01(\v2).flotestro.helper.v1.LocalAccountsRequestH\x00R\rlocalAccounts\x12Y\n" +
	"\x11local_user_action\x18\x1a \x01(\v2+.flotestro.helper.v1.LocalUserActionRequestH\x00R\x0flocalUserAction\x12R\n" +
	"\x0epackage_repair\x18\x1b \x01(\v2).flotestro.helper.v1.PackageRepairRequestH\x00R\rpackageRepair\x12I\n" +
	"\vdocker_read\x18\x1d \x01(\v2&.flotestro.helper.v1.DockerReadRequestH\x00R\n" +
	"dockerRead\x12O\n" +
	"\rdocker_action\x18\x1e \x01(\v2(.flotestro.helper.v1.DockerActionRequestH\x00R\fdockerAction\x12#\n" +
	"\rwant_progress\x18\x1c \x01(\bR\fwantProgressB\b\n" +
	"\x06action\",\n" +
	"\x14LocalAccountsRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x86\x03\n" +
	"\x16LocalUserActionRequest\x12S\n" +
	"\toperation\x18\x01 \x01(\x0e25.flotestro.helper.v1.LocalUserActionRequest.OperationR\toperation\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05gecos\x18\x03 \x01(\tR\x05gecos\x12\x14\n" +
	"\x05shell\x18\x04 \x01(\tR\x05shell\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\tR\x06groups\x12\x19\n" +
	"\bssh_keys\x18\x06 \x03(\tR\asshKeys\x12\x1f\n" +
	"\vcreate_home\x18\a \x01(\bR\n" +
	"createHome\"\x82\x01\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x12\n" +
	"\x0eOPERATION_LOCK\x10\x02\x12\x14\n" +
	"\x10OPERATION_UNLOCK\x10\x03\x12\x1a\n" +
	"\x16OPERATION_SET_SSH_KEYS\x10\x04\"\xca\x01\n" +
	"\x13DomainEnrollRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12*\n" +
	"\x11one_time_password\x18\x04 \x01(\tR\x0foneTimePassword\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12%\n" +
	"\x0epreflight_only\x18\x06 \x01(\bR\rpreflightOnly\".\n" +
	"\x14IdentityProbeRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"L\n" +
	"\rRebootRequest\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x80\x02\n" +
	"\x14PackageActionRequest\x12Q\n" +
	"\toperation\x18\x01 \x01(\x0e23.flotestro.helper.v1.PackageActionRequest.OperationR\toperation\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\x12#\n" +
	"\rsecurity_only\x18\x03 \x01(\bR\fsecurityOnly\"T\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OPERATION_REFRESH\x10\x01\x12\x15\n" +
	"\x11OPERATION_UPGRADE\x10\x02\"\xf5\x01\n" +
	"\x11UnitActionRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12N\n" +
	"\toperation\x18\x02 \x01(\x0e20.flotestro.helper.v1.UnitActionRequest.OperationR\toperation\"|\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_START\x10\x01\x12\x12\n" +
	"\x0eOPERATION_STOP\x10\x02\x12\x15\n" +
	"\x11OPERATION_RESTART\x10\x03\x12\x14\n" +
	"\x10OPERATION_RELOAD\x10\x04\"\xf3\a\n" +
	"\x0eHelperResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\fR\x06stderr\x12)\n" +
	"\x10output_truncated\x18\a \x01(\bR\x0foutputTruncated\x12A\n" +
	"\fstate_before\x18\b \x01(\v2\x1e.flotestro.helper.v1.UnitStateR\vstateBefore\x12?\n" +
	"\vstate_after\x18\t \x01(\v2\x1e.flotestro.helper.v1.UnitStateR\n" +
	"stateAfter\x12O\n" +
	"\x0epackage_result\x18\n" +
	" \x01(\v2(.flotestro.helper.v1.PackageActionResultR\rpackageResult\x12Q\n" +
	"\x0fidentity_result\x18\v \x01(\v2(.flotestro.helper.v1.IdentityProbeResultR\x0eidentityResult\x12L\n" +
	"\renroll_result\x18\f \x01(\v2'.flotestro.helper.v1.DomainEnrollResultR\fenrollResult\x12Q\n" +
	"\x0faccounts_result\x18\r \x01(\v2(.flotestro.helper.v1.LocalAccountsResultR\x0eaccountsResult\x12O\n" +
	"\rrepair_result\x18\x0e \x01(\v2*.flotestro.helper.v1.PackageRepairResponseR\frepairResult\x12=\n" +
	"\bprogress\x18\x0f \x01(\v2!.flotestro.helper.v1.TaskProgressR\bprogress\x12\x14\n" +
	"\x05final\x18\x10 \x01(\bR\x05final\x12J\n" +
	"\rdocker_result\x18\x11 \x01(\v2%.flotestro.helper.v1.DockerReadResultR\fdockerResult\x12Y\n" +
	"\x14docker_action_result\x18\x12 \x01(\v2'.flotestro.helper.v1.DockerActionResultR\x12dockerActionResult\"\x9a\x01\n" +
	"\x11DockerReadRequest\x12B\n" +
	"\x05scope\x18\x01 \x01(\x0e2,.flotestro.helper.v1.DockerReadRequest.ScopeR\x05scope\"A\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSCOPE_SUMMARY\x10\x01\x12\x0e\n" +
	"\n" +
	"SCOPE_FULL\x10\x02\"\x92\x04\n" +
	"\x13DockerActionRequest\x12P\n" +
	"\toperation\x18\x01 \x01(\x0e22.flotestro.helper.v1.DockerActionRequest.OperationR\toperation\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\x12%\n" +
	"\x0eremove_volumes\x18\x04 \x01(\bR\rremoveVolumes\x12'\n" +
	"\x0fimage_reference\x18\x05 \x01(\tR\x0eimageReference\x12\x1b\n" +
	"\timage_ids\x18\x06 \x03(\tR\bimageIds\x12!\n" +
	"\fvolume_names\x18\a \x03(\tR\vvolumeNames\x12\x1f\n" +
	"\vnetwork_ids\x18\b \x03(\tR\n" +
	"networkIds\"\xab\x01\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_START\x10\x01\x12\x12\n" +
	"\x0eOPERATION_STOP\x10\x02\x12\x15\n" +
	"\x11OPERATION_RESTART\x10\x03\x12\x14\n" +
	"\x10OPERATION_REMOVE\x10\x04\x12\x18\n" +
	"\x14OPERATION_PULL_IMAGE\x10\x05\x12\x13\n" +
	"\x0fOPERATION_PRUNE\x10\x06\"\xc1\x01\n" +
	"\x12DockerActionResult\x12\x16\n" +
	"\x06before\x18\x01 \x01(\fR\x06before\x12\x14\n" +
	"\x05after\x18\x02 \x01(\fR\x05after\x12\x18\n" +
	"\aremoved\x18\x03 \x03(\tR\aremoved\x12,\n" +
	"\x0freclaimed_bytes\x18\x04 \x01(\x03H\x00R\x0ereclaimedBytes\x88\x01\x01\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigestB\x12\n" +
	"\x10_reclaimed_bytes\"]\n" +
	"\x10DockerReadResult\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\x12-\n" +
	"\x12unavailable_reason\x18\x02 \x01(\tR\x11unavailableReason\"}\n" +
	"\fTaskProgress\x12\x12\n" +
	"\x04step\x18\x01 \x01(\rR\x04step\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x1d\n" +
	"\apercent\x18\x03 \x01(\rH\x00R\apercent\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessageB\n" +
	"\n" +
	"\b_percent\"\x89\x01\n" +
	"\x13LocalAccountsResult\x12C\n" +
	"\baccounts\x18\x01 \x03(\v2'.flotestro.helper.v1.LocalAccountDetailR\baccounts\x12-\n" +
	"\x12unavailable_reason\x18\x02 \x01(\tR\x11unavailableReason\"\xc6\x01\n" +
	"\x12LocalAccountDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\x06locked\x18\x02 \x01(\bH\x00R\x06locked\x88\x01\x01\x12;\n" +
	"\bssh_keys\x18\x03 \x03(\v2 .flotestro.helper.v1.LocalSSHKeyR\asshKeys\x12&\n" +
	"\fpassword_set\x18\x04 \x01(\bH\x01R\vpasswordSet\x88\x01\x01B\t\n" +
	"\a_lockedB\x0f\n" +
	"\r_password_set\"]\n" +
	"\vLocalSSHKey\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\xd9\x01\n" +
	"\x12DomainEnrollResult\x128\n" +
	"\x06checks\x18\x01 \x03(\v2 .flotestro.helper.v1.EnrollCheckR\x06checks\x12\x1a\n" +
	"\benrolled\x18\x02 \x01(\bR\benrolled\x12%\n" +
	"\x0ehost_principal\x18\x03 \x01(\tR\rhostPrincipal\x12F\n" +
	"\rverifications\x18\x04 \x03(\v2 .flotestro.helper.v1.EnrollCheckR\rverifications\"}\n" +
	"\vEnrollCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\x06passed\x18\x02 \x01(\bH\x00R\x06passed\x88\x01\x01\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1a\n" +
	"\bblocking\x18\x04 \x01(\bR\bblockingB\t\n" +
	"\a_passed\"\xc3\x02\n" +
	"\x13IdentityProbeResult\x12%\n" +
	"\x0ehost_principal\x18\x01 \x01(\tR\rhostPrincipal\x12$\n" +
	"\vkeytab_kvno\x18\x02 \x01(\rH\x00R\n" +
	"keytabKvno\x88\x01\x01\x12/\n" +
	"\x11cache_age_seconds\x18\x03 \x01(\x04H\x01R\x0fcacheAgeSeconds\x88\x01\x01\x12$\n" +
	"\vsssd_online\x18\x04 \x01(\bH\x02R\n" +
	"sssdOnline\x88\x01\x01\x12#\n" +
	"\rconfig_issues\x18\x05 \x03(\tR\fconfigIssues\x12-\n" +
	"\x12unavailable_reason\x18\x06 \x01(\tR\x11unavailableReasonB\x0e\n" +
	"\f_keytab_kvnoB\x14\n" +
	"\x12_cache_age_secondsB\x0e\n" +
	"\f_sssd_online\"\x86\x03\n" +
	"\x13PackageActionResult\x12\x18\n" +
	"\amanager\x18\x01 \x01(\tR\amanager\x12C\n" +
	"\aapplied\x18\x02 \x03(\v2).flotestro.helper.v1.PackageVersionChangeR\aapplied\x12'\n" +
	"\x0freboot_required\x18\x03 \x01(\bR\x0erebootRequired\x128\n" +
	"\x18services_needing_restart\x18\x04 \x03(\tR\x16servicesNeedingRestart\x126\n" +
	"\x17package_database_broken\x18\x05 \x01(\bR\x15packageDatabaseBroken\x12<\n" +
	"\x1apackages_needing_attention\x18\x06 \x03(\tR\x18packagesNeedingAttention\x12\x1f\n" +
	"\vself_repair\x18\a \x03(\tR\n" +
	"selfRepair\x12\x16\n" +
	"\x06output\x18\b \x03(\tR\x06output\"W\n" +
	"\x14PackageRepairRequest\x12?\n" +
	"\aanswers\x18\x01 \x03(\v2%.flotestro.helper.v1.DebconfSelectionR\aanswers\"r\n" +
	"\x10DebconfSelection\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\xb9\x01\n" +
	"\x15PackageRepairResponse\x12\x18\n" +
	"\amanager\x18\x01 \x01(\tR\amanager\x12N\n" +
	"\rstill_blocked\x18\x02 \x03(\v2).flotestro.helper.v1.BlockedPackageDetailR\fstillBlocked\x12\x1a\n" +
	"\banswered\x18\x03 \x03(\tR\banswered\x12\x1a\n" +
	"\brepaired\x18\x04 \x01(\bR\brepaired\"\x8c\x01\n" +
	"\x14BlockedPackageDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12H\n" +
	"\tquestions\x18\x03 \x03(\v2*.flotestro.helper.v1.DebconfQuestionDetailR\tquestions\"o\n" +
	"\x15DebconfQuestionDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\banswered\x18\x03 \x01(\bH\x00R\banswered\x88\x01\x01B\v\n" +
	"\t_answered\"v\n" +
	"\x14PackageVersionChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eversion_before\x18\x02 \x01(\tR\rversionBefore\x12#\n" +
	"\rversion_after\x18\x03 \x01(\tR\fversionAfter\"\xf8\x01\n" +
	"\tUnitState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"load_state\x18\x02 \x01(\tR\tloadState\x12!\n" +
	"\factive_state\x18\x03 \x01(\tR\vactiveState\x12\x1b\n" +
	"\tsub_state\x18\x04 \x01(\tR\bsubState\x12&\n" +
	"\x0funit_file_state\x18\x05 \x01(\tR\runitFileState\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x19\n" +
	"\bmain_pid\x18\a \x01(\rR\amainPid\x12\x1d\n" +
	"\n" +
	"n_restarts\x18\b \x01(\rR\tnRestartsBOZMgithub.com/ultherego/flotestro/internal/genproto/flotestro/helper/v1;helperv1b\x06proto3"

var (
	file_flotestro_helper_v1_helper_proto_rawDescOnce sync.Once
	file_flotestro_helper_v1_helper_proto_rawDescData []byte
)

func file_flotestro_helper_v1_helper_proto_rawDescGZIP() []byte {
	file_flotestro_helper_v1_helper_proto_rawDescOnce.Do(func() {
		file_flotestro_helper_v1_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flotestro_helper_v1_helper_proto_rawDesc), len(file_flotestro_helper_v1_helper_proto_rawDesc)))
	})
	return file_flotestro_helper_v1_helper_proto_rawDescData
}

var file_flotestro_helper_v1_helper_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_flotestro_helper_v1_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_flotestro_helper_v1_helper_proto_goTypes = []any{
	(LocalUserActionRequest_Operation)(0), // 0: flotestro.helper.v1.LocalUserActionRequest.Operation
	(PackageActionRequest_Operation)(0),   // 1: flotestro.helper.v1.PackageActionRequest.Operation
	(UnitActionRequest_Operation)(0),      // 2: flotestro.helper.v1.UnitActionRequest.Operation
	(DockerReadRequest_Scope)(0),          // 3: flotestro.helper.v1.DockerReadRequest.Scope
	(DockerActionRequest_Operation)(0),    // 4: flotestro.helper.v1.DockerActionRequest.Operation
	(*HelperRequest)(nil),                 // 5: flotestro.helper.v1.HelperRequest
	(*LocalAccountsRequest)(nil),          // 6: flotestro.helper.v1.LocalAccountsRequest
	(*LocalUserActionRequest)(nil),        // 7: flotestro.helper.v1.LocalUserActionRequest
	(*DomainEnrollRequest)(nil),           // 8: flotestro.helper.v1.DomainEnrollRequest
	(*IdentityProbeRequest)(nil),          // 9: flotestro.helper.v1.IdentityProbeRequest
	(*RebootRequest)(nil),                 // 10: flotestro.helper.v1.RebootRequest
	(*PackageActionRequest)(nil),          // 11: flotestro.helper.v1.PackageActionRequest
	(*UnitActionRequest)(nil),             // 12: flotestro.helper.v1.UnitActionRequest
	(*HelperResponse)(nil),                // 13: flotestro.helper.v1.HelperResponse
	(*DockerReadRequest)(nil),             // 14: flotestro.helper.v1.DockerReadRequest
	(*DockerActionRequest)(nil),           // 15: flotestro.helper.v1.DockerActionRequest
	(*DockerActionResult)(nil),            // 16: flotestro.helper.v1.DockerActionResult
	(*DockerReadResult)(nil),              // 17: flotestro.helper.v1.DockerReadResult
	(*TaskProgress)(nil),                  // 18: flotestro.helper.v1.TaskProgress
	(*LocalAccountsResult)(nil),           // 19: flotestro.helper.v1.LocalAccountsResult
	(*LocalAccountDetail)(nil),            // 20: flotestro.helper.v1.LocalAccountDetail
	(*LocalSSHKey)(nil),                   // 21: flotestro.helper.v1.LocalSSHKey
	(*DomainEnrollResult)(nil),            // 22: flotestro.helper.v1.DomainEnrollResult
	(*EnrollCheck)(nil),                   // 23: flotestro.helper.v1.EnrollCheck
	(*IdentityProbeResult)(nil),           // 24: flotestro.helper.v1.IdentityProbeResult
	(*PackageActionResult)(nil),           // 25: flotestro.helper.v1.PackageActionResult
	(*PackageRepairRequest)(nil),          // 26: flotestro.helper.v1.PackageRepairRequest
	(*DebconfSelection)(nil),              // 27: flotestro.helper.v1.DebconfSelection
	(*PackageRepairResponse)(nil),         // 28: flotestro.helper.v1.PackageRepairResponse
	(*BlockedPackageDetail)(nil),          // 29: flotestro.helper.v1.BlockedPackageDetail
	(*DebconfQuestionDetail)(nil),         // 30: flotestro.helper.v1.DebconfQuestionDetail
	(*PackageVersionChange)(nil),          // 31: flotestro.helper.v1.PackageVersionChange
	(*UnitState)(nil),                     // 32: flotestro.helper.v1.UnitState
	(*timestamppb.Timestamp)(nil),         // 33: google.protobuf.Timestamp
}
var file_flotestro_helper_v1_helper_proto_depIdxs = []int32{
	33, // 0: flotestro.helper.v1.HelperRequest.expires_at:type_name -> google.protobuf.Timestamp
	12, // 1: flotestro.helper.v1.HelperRequest.unit_action:type_name -> flotestro.helper.v1.UnitActionRequest
	11, // 2: flotestro.helper.v1.HelperRequest.package_action:type_name -> flotestro.helper.v1.PackageActionRequest
	10, // 3: flotestro.helper.v1.HelperRequest.reboot:type_name -> flotestro.helper.v1.RebootRequest
	9,  // 4: flotestro.helper.v1.HelperRequest.identity_probe:type_name -> flotestro.helper.v1.IdentityProbeRequest
	8,  // 5: flotestro.helper.v1.HelperRequest.domain_enroll:type_name -> flotestro.helper.v1.DomainEnrollRequest
	6,  // 6: flotestro.helper.v1.HelperRequest.local_accounts:type_name -> flotestro.helper.v1.LocalAccountsRequest
	7,  // 7: flotestro.helper.v1.HelperRequest.local_user_action:type_name -> flotestro.helper.v1.LocalUserActionRequest
	26, // 8: flotestro.helper.v1.HelperRequest.package_repair:type_name -> flotestro.helper.v1.PackageRepairRequest
	14, // 9: flotestro.helper.v1.HelperRequest.docker_read:type_name -> flotestro.helper.v1.DockerReadRequest
	15, // 10: flotestro.helper.v1.HelperRequest.docker_action:type_name -> flotestro.helper.v1.DockerActionRequest
	0,  // 11: flotestro.helper.v1.LocalUserActionRequest.operation:type_name -> flotestro.helper.v1.LocalUserActionRequest.Operation
	1,  // 12: flotestro.helper.v1.PackageActionRequest.operation:type_name -> flotestro.helper.v1.PackageActionRequest.Operation
	2,  // 13: flotestro.helper.v1.UnitActionRequest.operation:type_name -> flotestro.helper.v1.UnitActionRequest.Operation
	32, // 14: flotestro.helper.v1.HelperResponse.state_before:type_name -> flotestro.helper.v1.UnitState
	32, // 15: flotestro.helper.v1.HelperResponse.state_after:type_name -> flotestro.helper.v1.UnitState
	25, // 16: flotestro.helper.v1.HelperResponse.package_result:type_name -> flotestro.helper.v1.PackageActionResult
	24, // 17: flotestro.helper.v1.HelperResponse.identity_result:type_name -> flotestro.helper.v1.IdentityProbeResult
	22, // 18: flotestro.helper.v1.HelperResponse.enroll_result:type_name -> flotestro.helper.v1.DomainEnrollResult
	19, // 19: flotestro.helper.v1.HelperResponse.accounts_result:type_name -> flotestro.helper.v1.LocalAccountsResult
	28, // 20: flotestro.helper.v1.HelperResponse.repair_result:type_name -> flotestro.helper.v1.PackageRepairResponse
	18, // 21: flotestro.helper.v1.HelperResponse.progress:type_name -> flotestro.helper.v1.TaskProgress
	17, // 22: flotestro.helper.v1.HelperResponse.docker_result:type_name -> flotestro.helper.v1.DockerReadResult
	16, // 23: flotestro.helper.v1.HelperResponse.docker_action_result:type_name -> flotestro.helper.v1.DockerActionResult
	3,  // 24: flotestro.helper.v1.DockerReadRequest.scope:type_name -> flotestro.helper.v1.DockerReadRequest.Scope
	4,  // 25: flotestro.helper.v1.DockerActionRequest.operation:type_name -> flotestro.helper.v1.DockerActionRequest.Operation
	20, // 26: flotestro.helper.v1.LocalAccountsResult.accounts:type_name -> flotestro.helper.v1.LocalAccountDetail
	21, // 27: flotestro.helper.v1.LocalAccountDetail.ssh_keys:type_name -> flotestro.helper.v1.LocalSSHKey
	23, // 28: flotestro.helper.v1.DomainEnrollResult.checks:type_name -> flotestro.helper.v1.EnrollCheck
	23, // 29: flotestro.helper.v1.DomainEnrollResult.verifications:type_name -> flotestro.helper.v1.EnrollCheck
	31, // 30: flotestro.helper.v1.PackageActionResult.applied:type_name -> flotestro.helper.v1.PackageVersionChange
	27, // 31: flotestro.helper.v1.PackageRepairRequest.answers:type_name -> flotestro.helper.v1.DebconfSelection
	29, // 32: flotestro.helper.v1.PackageRepairResponse.still_blocked:type_name -> flotestro.helper.v1.BlockedPackageDetail
	30, // 33: flotestro.helper.v1.BlockedPackageDetail.questions:type_name -> flotestro.helper.v1.DebconfQuestionDetail
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_flotestro_helper_v1_helper_proto_init() }
func file_flotestro_helper_v1_helper_proto_init() {
	if File_flotestro_helper_v1_helper_proto != nil {
		return
	}
	file_flotestro_helper_v1_helper_proto_msgTypes[0].OneofWrappers = []any{
		(*HelperRequest_UnitAction)(nil),
		(*HelperRequest_PackageAction)(nil),
		(*HelperRequest_Reboot)(nil),
		(*HelperRequest_IdentityProbe)(nil),
		(*HelperRequest_DomainEnroll)(nil),
		(*HelperRequest_LocalAccounts)(nil),
		(*HelperRequest_LocalUserAction)(nil),
		(*HelperRequest_PackageRepair)(nil),
		(*HelperRequest_DockerRead)(nil),
		(*HelperRequest_DockerAction)(nil),
	}
	file_flotestro_helper_v1_helper_proto_msgTypes[11].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[13].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[15].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[18].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[19].OneofWrappers = []any{}
	file_flotestro_helper_v1_helper_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flotestro_helper_v1_helper_proto_rawDesc), len(file_flotestro_helper_v1_helper_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flotestro_helper_v1_helper_proto_goTypes,
		DependencyIndexes: file_flotestro_helper_v1_helper_proto_depIdxs,
		EnumInfos:         file_flotestro_helper_v1_helper_proto_enumTypes,
		MessageInfos:      file_flotestro_helper_v1_helper_proto_msgTypes,
	}.Build()
	File_flotestro_helper_v1_helper_proto = out.File
	file_flotestro_helper_v1_helper_proto_goTypes = nil
	file_flotestro_helper_v1_helper_proto_depIdxs = nil
}
