// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: flotestro/helper/v1/helper.proto

package helperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageActionRequest_Operation int32

const (
	PackageActionRequest_OPERATION_UNSPECIFIED PackageActionRequest_Operation = 0
	// Odswiezenie metadanych repozytorium.
	PackageActionRequest_OPERATION_REFRESH PackageActionRequest_Operation = 1
	// Wykonanie transakcji aktualizacji.
	PackageActionRequest_OPERATION_UPGRADE PackageActionRequest_Operation = 2
)

// Enum value maps for PackageActionRequest_Operation.
var (
	PackageActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_REFRESH",
		2: "OPERATION_UPGRADE",
	}
	PackageActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_REFRESH":     1,
		"OPERATION_UPGRADE":     2,
	}
)

func (x PackageActionRequest_Operation) Enum() *PackageActionRequest_Operation {
	p := new(PackageActionRequest_Operation)
	*p = x
	return p
}

func (x PackageActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[0].Descriptor()
}

func (PackageActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[0]
}

func (x PackageActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageActionRequest_Operation.Descriptor instead.
func (PackageActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{2, 0}
}

type UnitActionRequest_Operation int32

const (
	UnitActionRequest_OPERATION_UNSPECIFIED UnitActionRequest_Operation = 0
	UnitActionRequest_OPERATION_START       UnitActionRequest_Operation = 1
	UnitActionRequest_OPERATION_STOP        UnitActionRequest_Operation = 2
	UnitActionRequest_OPERATION_RESTART     UnitActionRequest_Operation = 3
	UnitActionRequest_OPERATION_RELOAD      UnitActionRequest_Operation = 4
)

// Enum value maps for UnitActionRequest_Operation.
var (
	UnitActionRequest_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_START",
		2: "OPERATION_STOP",
		3: "OPERATION_RESTART",
		4: "OPERATION_RELOAD",
	}
	UnitActionRequest_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_START":       1,
		"OPERATION_STOP":        2,
		"OPERATION_RESTART":     3,
		"OPERATION_RELOAD":      4,
	}
)

func (x UnitActionRequest_Operation) Enum() *UnitActionRequest_Operation {
	p := new(UnitActionRequest_Operation)
	*p = x
	return p
}

func (x UnitActionRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitActionRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_flotestro_helper_v1_helper_proto_enumTypes[1].Descriptor()
}

func (UnitActionRequest_Operation) Type() protoreflect.EnumType {
	return &file_flotestro_helper_v1_helper_proto_enumTypes[1]
}

func (x UnitActionRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitActionRequest_Operation.Descriptor instead.
func (UnitActionRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{3, 0}
}

// PROTOCOL_VERSION zmienia sie przy kazdej niezgodnej zmianie kontraktu.
// Helper odrzuca wersje, ktorej nie zna, zamiast zgadywac znaczenie pol.
type HelperRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Helper odrzuca zadanie po terminie, niezaleznie od tego, co twierdzi agent.
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxOutputBytes uint32                 `protobuf:"varint,5,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*HelperRequest_UnitAction
	//	*HelperRequest_PackageAction
	//	*HelperRequest_Reboot
	Action        isHelperRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperRequest) Reset() {
	*x = HelperRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperRequest) ProtoMessage() {}

func (x *HelperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperRequest.ProtoReflect.Descriptor instead.
func (*HelperRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{0}
}

func (x *HelperRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelperRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HelperRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *HelperRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HelperRequest) GetMaxOutputBytes() uint32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *HelperRequest) GetAction() isHelperRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *HelperRequest) GetUnitAction() *UnitActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_UnitAction); ok {
			return x.UnitAction
		}
	}
	return nil
}

func (x *HelperRequest) GetPackageAction() *PackageActionRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_PackageAction); ok {
			return x.PackageAction
		}
	}
	return nil
}

func (x *HelperRequest) GetReboot() *RebootRequest {
	if x != nil {
		if x, ok := x.Action.(*HelperRequest_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

type isHelperRequest_Action interface {
	isHelperRequest_Action()
}

type HelperRequest_UnitAction struct {
	UnitAction *UnitActionRequest `protobuf:"bytes,20,opt,name=unit_action,json=unitAction,proto3,oneof"`
}

type HelperRequest_PackageAction struct {
	PackageAction *PackageActionRequest `protobuf:"bytes,21,opt,name=package_action,json=packageAction,proto3,oneof"`
}

type HelperRequest_Reboot struct {
	Reboot *RebootRequest `protobuf:"bytes,22,opt,name=reboot,proto3,oneof"`
}

func (*HelperRequest_UnitAction) isHelperRequest_Action() {}

func (*HelperRequest_PackageAction) isHelperRequest_Action() {}

func (*HelperRequest_Reboot) isHelperRequest_Action() {}

// RebootRequest zleca kontrolowany restart hosta.
type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelaySeconds  uint32                 `protobuf:"varint,1,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{1}
}

func (x *RebootRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *RebootRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PackageActionRequest obejmuje operacje pakietowe wymagajace roota.
// Planowanie w trybie symulacji nie wymaga roota i nie idzie przez helper.
type PackageActionRequest struct {
	state     protoimpl.MessageState         `protogen:"open.v1"`
	Operation PackageActionRequest_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=flotestro.helper.v1.PackageActionRequest_Operation" json:"operation,omitempty"`
	// Pusta lista przy OPERATION_UPGRADE oznacza wszystkie aktualizacje.
	Packages      []string `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	SecurityOnly  bool     `protobuf:"varint,3,opt,name=security_only,json=securityOnly,proto3" json:"security_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageActionRequest) Reset() {
	*x = PackageActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageActionRequest) ProtoMessage() {}

func (x *PackageActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageActionRequest.ProtoReflect.Descriptor instead.
func (*PackageActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{2}
}

func (x *PackageActionRequest) GetOperation() PackageActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return PackageActionRequest_OPERATION_UNSPECIFIED
}

func (x *PackageActionRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackageActionRequest) GetSecurityOnly() bool {
	if x != nil {
		return x.SecurityOnly
	}
	return false
}

type UnitActionRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Unit          string                      `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Operation     UnitActionRequest_Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=flotestro.helper.v1.UnitActionRequest_Operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitActionRequest) Reset() {
	*x = UnitActionRequest{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitActionRequest) ProtoMessage() {}

func (x *UnitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitActionRequest.ProtoReflect.Descriptor instead.
func (*UnitActionRequest) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{3}
}

func (x *UnitActionRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitActionRequest) GetOperation() UnitActionRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return UnitActionRequest_OPERATION_UNSPECIFIED
}

type HelperResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Stabilny kod maszynowy: unknown_action, unsupported_version, expired,
	// protected_unit, invalid_unit, locked, exec_failed, timeout.
	ErrorCode       string               `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode        int32                `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          []byte               `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          []byte               `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	OutputTruncated bool                 `protobuf:"varint,7,opt,name=output_truncated,json=outputTruncated,proto3" json:"output_truncated,omitempty"`
	StateBefore     *UnitState           `protobuf:"bytes,8,opt,name=state_before,json=stateBefore,proto3" json:"state_before,omitempty"`
	StateAfter      *UnitState           `protobuf:"bytes,9,opt,name=state_after,json=stateAfter,proto3" json:"state_after,omitempty"`
	PackageResult   *PackageActionResult `protobuf:"bytes,10,opt,name=package_result,json=packageResult,proto3" json:"package_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelperResponse) Reset() {
	*x = HelperResponse{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperResponse) ProtoMessage() {}

func (x *HelperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperResponse.ProtoReflect.Descriptor instead.
func (*HelperResponse) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{4}
}

func (x *HelperResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelperResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *HelperResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelperResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *HelperResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *HelperResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *HelperResponse) GetOutputTruncated() bool {
	if x != nil {
		return x.OutputTruncated
	}
	return false
}

func (x *HelperResponse) GetStateBefore() *UnitState {
	if x != nil {
		return x.StateBefore
	}
	return nil
}

func (x *HelperResponse) GetStateAfter() *UnitState {
	if x != nil {
		return x.StateAfter
	}
	return nil
}

func (x *HelperResponse) GetPackageResult() *PackageActionResult {
	if x != nil {
		return x.PackageResult
	}
	return nil
}

type PackageActionResult struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Manager                string                  `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	Applied                []*PackageVersionChange `protobuf:"bytes,2,rep,name=applied,proto3" json:"applied,omitempty"`
	RebootRequired         bool                    `protobuf:"varint,3,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	ServicesNeedingRestart []string                `protobuf:"bytes,4,rep,name=services_needing_restart,json=servicesNeedingRestart,proto3" json:"services_needing_restart,omitempty"`
	// Prawda, gdy baza pakietow wymaga naprawy po nieudanej transakcji.
	PackageDatabaseBroken bool `protobuf:"varint,5,opt,name=package_database_broken,json=packageDatabaseBroken,proto3" json:"package_database_broken,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PackageActionResult) Reset() {
	*x = PackageActionResult{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageActionResult) ProtoMessage() {}

func (x *PackageActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageActionResult.ProtoReflect.Descriptor instead.
func (*PackageActionResult) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{5}
}

func (x *PackageActionResult) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *PackageActionResult) GetApplied() []*PackageVersionChange {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *PackageActionResult) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *PackageActionResult) GetServicesNeedingRestart() []string {
	if x != nil {
		return x.ServicesNeedingRestart
	}
	return nil
}

func (x *PackageActionResult) GetPackageDatabaseBroken() bool {
	if x != nil {
		return x.PackageDatabaseBroken
	}
	return false
}

type PackageVersionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionBefore string                 `protobuf:"bytes,2,opt,name=version_before,json=versionBefore,proto3" json:"version_before,omitempty"`
	VersionAfter  string                 `protobuf:"bytes,3,opt,name=version_after,json=versionAfter,proto3" json:"version_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageVersionChange) Reset() {
	*x = PackageVersionChange{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageVersionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageVersionChange) ProtoMessage() {}

func (x *PackageVersionChange) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageVersionChange.ProtoReflect.Descriptor instead.
func (*PackageVersionChange) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{6}
}

func (x *PackageVersionChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageVersionChange) GetVersionBefore() string {
	if x != nil {
		return x.VersionBefore
	}
	return ""
}

func (x *PackageVersionChange) GetVersionAfter() string {
	if x != nil {
		return x.VersionAfter
	}
	return ""
}

type UnitState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LoadState     string                 `protobuf:"bytes,2,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	ActiveState   string                 `protobuf:"bytes,3,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	SubState      string                 `protobuf:"bytes,4,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`
	UnitFileState string                 `protobuf:"bytes,5,opt,name=unit_file_state,json=unitFileState,proto3" json:"unit_file_state,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	MainPid       uint32                 `protobuf:"varint,7,opt,name=main_pid,json=mainPid,proto3" json:"main_pid,omitempty"`
	NRestarts     uint32                 `protobuf:"varint,8,opt,name=n_restarts,json=nRestarts,proto3" json:"n_restarts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitState) Reset() {
	*x = UnitState{}
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitState) ProtoMessage() {}

func (x *UnitState) ProtoReflect() protoreflect.Message {
	mi := &file_flotestro_helper_v1_helper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitState.ProtoReflect.Descriptor instead.
func (*UnitState) Descriptor() ([]byte, []int) {
	return file_flotestro_helper_v1_helper_proto_rawDescGZIP(), []int{7}
}

func (x *UnitState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitState) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *UnitState) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *UnitState) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *UnitState) GetUnitFileState() string {
	if x != nil {
		return x.UnitFileState
	}
	return ""
}

func (x *UnitState) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *UnitState) GetMainPid() uint32 {
	if x != nil {
		return x.MainPid
	}
	return 0
}

func (x *UnitState) GetNRestarts() uint32 {
	if x != nil {
		return x.NRestarts
	}
	return 0
}

var File_flotestro_helper_v1_helper_proto protoreflect.FileDescriptor

const file_flotestro_helper_v1_helper_proto_rawDesc = "" +
	"\n" +
	" flotestro/helper/v1/helper.proto\x12\x13flotestro.helper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x03\n" +
	"\rHelperRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12(\n" +
	"\x10max_output_bytes\x18\x05 \x01(\rR\x0emaxOutputBytes\x12I\n" +
	"\vunit_action\x18\x14 \x01(\v2&.flotestro.helper.v1.UnitActionRequestH\x00R\n" +
	"unitAction\x12R\n" +
	"\x0epackage_action\x18\x15 \x01(\v2).flotestro.helper.v1.PackageActionRequestH\x00R\rpackageAction\x12<\n" +
	"\x06reboot\x18\x16 \x01(\v2\".flotestro.helper.v1.RebootRequestH\x00R\x06rebootB\b\n" +
	"\x06action\"L\n" +
	"\rRebootRequest\x12#\n" +
	"\rdelay_seconds\x18\x01 \x01(\rR\fdelaySeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x80\x02\n" +
	"\x14PackageActionRequest\x12Q\n" +
	"\toperation\x18\x01 \x01(\x0e23.flotestro.helper.v1.PackageActionRequest.OperationR\toperation\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\x12#\n" +
	"\rsecurity_only\x18\x03 \x01(\bR\fsecurityOnly\"T\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OPERATION_REFRESH\x10\x01\x12\x15\n" +
	"\x11OPERATION_UPGRADE\x10\x02\"\xf5\x01\n" +
	"\x11UnitActionRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12N\n" +
	"\toperation\x18\x02 \x01(\x0e20.flotestro.helper.v1.UnitActionRequest.OperationR\toperation\"|\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_START\x10\x01\x12\x12\n" +
	"\x0eOPERATION_STOP\x10\x02\x12\x15\n" +
	"\x11OPERATION_RESTART\x10\x03\x12\x14\n" +
	"\x10OPERATION_RELOAD\x10\x04\"\xb2\x03\n" +
	"\x0eHelperResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\fR\x06stderr\x12)\n" +
	"\x10output_truncated\x18\a \x01(\bR\x0foutputTruncated\x12A\n" +
	"\fstate_before\x18\b \x01(\v2\x1e.flotestro.helper.v1.UnitStateR\vstateBefore\x12?\n" +
	"\vstate_after\x18\t \x01(\v2\x1e.flotestro.helper.v1.UnitStateR\n" +
	"stateAfter\x12O\n" +
	"\x0epackage_result\x18\n" +
	" \x01(\v2(.flotestro.helper.v1.PackageActionResultR\rpackageResult\"\x8f\x02\n" +
	"\x13PackageActionResult\x12\x18\n" +
	"\amanager\x18\x01 \x01(\tR\amanager\x12C\n" +
	"\aapplied\x18\x02 \x03(\v2).flotestro.helper.v1.PackageVersionChangeR\aapplied\x12'\n" +
	"\x0freboot_required\x18\x03 \x01(\bR\x0erebootRequired\x128\n" +
	"\x18services_needing_restart\x18\x04 \x03(\tR\x16servicesNeedingRestart\x126\n" +
	"\x17package_database_broken\x18\x05 \x01(\bR\x15packageDatabaseBroken\"v\n" +
	"\x14PackageVersionChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eversion_before\x18\x02 \x01(\tR\rversionBefore\x12#\n" +
	"\rversion_after\x18\x03 \x01(\tR\fversionAfter\"\xf8\x01\n" +
	"\tUnitState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"load_state\x18\x02 \x01(\tR\tloadState\x12!\n" +
	"\factive_state\x18\x03 \x01(\tR\vactiveState\x12\x1b\n" +
	"\tsub_state\x18\x04 \x01(\tR\bsubState\x12&\n" +
	"\x0funit_file_state\x18\x05 \x01(\tR\runitFileState\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x19\n" +
	"\bmain_pid\x18\a \x01(\rR\amainPid\x12\x1d\n" +
	"\n" +
	"n_restarts\x18\b \x01(\rR\tnRestartsBOZMgithub.com/ultherego/flotestro/internal/genproto/flotestro/helper/v1;helperv1b\x06proto3"

var (
	file_flotestro_helper_v1_helper_proto_rawDescOnce sync.Once
	file_flotestro_helper_v1_helper_proto_rawDescData []byte
)

func file_flotestro_helper_v1_helper_proto_rawDescGZIP() []byte {
	file_flotestro_helper_v1_helper_proto_rawDescOnce.Do(func() {
		file_flotestro_helper_v1_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flotestro_helper_v1_helper_proto_rawDesc), len(file_flotestro_helper_v1_helper_proto_rawDesc)))
	})
	return file_flotestro_helper_v1_helper_proto_rawDescData
}

var file_flotestro_helper_v1_helper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flotestro_helper_v1_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_flotestro_helper_v1_helper_proto_goTypes = []any{
	(PackageActionRequest_Operation)(0), // 0: flotestro.helper.v1.PackageActionRequest.Operation
	(UnitActionRequest_Operation)(0),    // 1: flotestro.helper.v1.UnitActionRequest.Operation
	(*HelperRequest)(nil),               // 2: flotestro.helper.v1.HelperRequest
	(*RebootRequest)(nil),               // 3: flotestro.helper.v1.RebootRequest
	(*PackageActionRequest)(nil),        // 4: flotestro.helper.v1.PackageActionRequest
	(*UnitActionRequest)(nil),           // 5: flotestro.helper.v1.UnitActionRequest
	(*HelperResponse)(nil),              // 6: flotestro.helper.v1.HelperResponse
	(*PackageActionResult)(nil),         // 7: flotestro.helper.v1.PackageActionResult
	(*PackageVersionChange)(nil),        // 8: flotestro.helper.v1.PackageVersionChange
	(*UnitState)(nil),                   // 9: flotestro.helper.v1.UnitState
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
}
var file_flotestro_helper_v1_helper_proto_depIdxs = []int32{
	10, // 0: flotestro.helper.v1.HelperRequest.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 1: flotestro.helper.v1.HelperRequest.unit_action:type_name -> flotestro.helper.v1.UnitActionRequest
	4,  // 2: flotestro.helper.v1.HelperRequest.package_action:type_name -> flotestro.helper.v1.PackageActionRequest
	3,  // 3: flotestro.helper.v1.HelperRequest.reboot:type_name -> flotestro.helper.v1.RebootRequest
	0,  // 4: flotestro.helper.v1.PackageActionRequest.operation:type_name -> flotestro.helper.v1.PackageActionRequest.Operation
	1,  // 5: flotestro.helper.v1.UnitActionRequest.operation:type_name -> flotestro.helper.v1.UnitActionRequest.Operation
	9,  // 6: flotestro.helper.v1.HelperResponse.state_before:type_name -> flotestro.helper.v1.UnitState
	9,  // 7: flotestro.helper.v1.HelperResponse.state_after:type_name -> flotestro.helper.v1.UnitState
	7,  // 8: flotestro.helper.v1.HelperResponse.package_result:type_name -> flotestro.helper.v1.PackageActionResult
	8,  // 9: flotestro.helper.v1.PackageActionResult.applied:type_name -> flotestro.helper.v1.PackageVersionChange
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_flotestro_helper_v1_helper_proto_init() }
func file_flotestro_helper_v1_helper_proto_init() {
	if File_flotestro_helper_v1_helper_proto != nil {
		return
	}
	file_flotestro_helper_v1_helper_proto_msgTypes[0].OneofWrappers = []any{
		(*HelperRequest_UnitAction)(nil),
		(*HelperRequest_PackageAction)(nil),
		(*HelperRequest_Reboot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flotestro_helper_v1_helper_proto_rawDesc), len(file_flotestro_helper_v1_helper_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flotestro_helper_v1_helper_proto_goTypes,
		DependencyIndexes: file_flotestro_helper_v1_helper_proto_depIdxs,
		EnumInfos:         file_flotestro_helper_v1_helper_proto_enumTypes,
		MessageInfos:      file_flotestro_helper_v1_helper_proto_msgTypes,
	}.Build()
	File_flotestro_helper_v1_helper_proto = out.File
	file_flotestro_helper_v1_helper_proto_goTypes = nil
	file_flotestro_helper_v1_helper_proto_depIdxs = nil
}
