package dns

import "testing"

// Wyjscie przepisane z hosta floty testowej.
const wyjscieResolvectl = `Global
         Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 192.168.56.50
       DNS Servers: 192.168.56.50
        DNS Domain: ~flotestro.test

Link 2 (enp0s3)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute LLMNR=resolve -mDNS -DNSOverTLS
                    DNSSEC=no/unsupported
Current DNS Server: 10.0.2.3
       DNS Servers: 10.0.2.3
        DNS Domain: vcmts-wawPereca-1.vectranet.pl
     Default Route: yes

Link 3 (enp0s8)
    Current Scopes: LLMNR/IPv4 LLMNR/IPv6
         Protocols: -DefaultRoute LLMNR=resolve -mDNS -DNSOverTLS
                    DNSSEC=no/unsupported
     Default Route: no`

// Host w domenie ma serwer katalogu na jednym linku i serwer dostawcy na
// drugim. Zlanie ich w jedna liste ukrywaloby to, ktory serwer odpowie.
func TestResolverRozdzielaSerweryPoLinkach(t *testing.T) {
	snapshot := ParsujResolvectl(wyjscieResolvectl)

	if snapshot.Mode != "stub" {
		t.Errorf("tryb = %q", snapshot.Mode)
	}
	if len(snapshot.Servers) != 1 || snapshot.Servers[0] != "192.168.56.50" {
		t.Errorf("serwery globalne = %v", snapshot.Servers)
	}
	if len(snapshot.Links) != 2 {
		t.Fatalf("linkow = %d", len(snapshot.Links))
	}
	po := map[string]Link{}
	for _, link := range snapshot.Links {
		po[link.Name] = link
	}
	if len(po["enp0s3"].Servers) != 1 || po["enp0s3"].Servers[0] != "10.0.2.3" {
		t.Errorf("serwery enp0s3 = %v", po["enp0s3"].Servers)
	}
	// Link bez wlasnego serwera nie moze odziedziczyc cudzego.
	if len(po["enp0s8"].Servers) != 0 {
		t.Errorf("serwery enp0s8 = %v", po["enp0s8"].Servers)
	}
	// Trasa domyslna rozstrzyga, ktory link odpowiada na nazwy spoza
	// swoich domen.
	if po["enp0s3"].DefaultRoute == nil || !*po["enp0s3"].DefaultRoute {
		t.Errorf("trasa domyslna enp0s3 = %v", po["enp0s3"].DefaultRoute)
	}
	if po["enp0s8"].DefaultRoute == nil || *po["enp0s8"].DefaultRoute {
		t.Errorf("trasa domyslna enp0s8 = %v", po["enp0s8"].DefaultRoute)
	}
	// Protokoly lamia sie na dwa wiersze, wiec DNSSEC linku jest w drugim.
	if po["enp0s3"].DNSSEC != "no/unsupported" || po["enp0s3"].DNSOverTLS != "no" {
		t.Errorf("protokoly enp0s3 = %q / %q", po["enp0s3"].DNSSEC, po["enp0s3"].DNSOverTLS)
	}
	if snapshot.Links[0].Index != 2 {
		t.Errorf("numer linku = %d", snapshot.Links[0].Index)
	}
}

func TestPlikResolveraCzytaSerweryIDomeny(t *testing.T) {
	tresc := `# Generated by dhcpcd from eth0.dhcp, eth0.ra
domain vcmts-wawPereca-1.vectranet.pl
nameserver 10.0.2.3
nameserver fd17:625c:f037:2::3
search flotestro.test example.test`
	serwery, domeny := ParsujResolvConf(tresc)
	if len(serwery) != 2 || serwery[1] != "fd17:625c:f037:2::3" {
		t.Errorf("serwery = %v", serwery)
	}
	if len(domeny) != 3 {
		t.Errorf("domeny = %v", domeny)
	}
}

// Wlasciciel pliku rozstrzyga, czy panel moze cokolwiek zmienic: plik
// nalezacy do uslugi zostanie i tak nadpisany.
func TestWlascicielPlikuJestRozpoznawany(t *testing.T) {
	przypadki := []struct {
		cel, tresc, chciany string
	}{
		{"../run/systemd/resolve/stub-resolv.conf", "", WlascicielResolved},
		{"/run/NetworkManager/resolv.conf", "", WlascicielNM},
		{"", "# Generated by dhcpcd from eth0.dhcp\nnameserver 10.0.2.3", WlascicielDHCP},
		{"", "# This file is managed by man:systemd-resolved(8)", WlascicielResolved},
		{"", "nameserver 10.0.0.1", WlascicielReczny},
		// Pusty plik nie mowi nic o wlascicielu, a zgadywanie zachecaloby
		// panel do pisania po czyms, czego nie rozumie.
		{"", "", WlascicielNieznany},
	}
	for _, przypadek := range przypadki {
		if wynik := WlascicielResolvConf(przypadek.cel, przypadek.tresc); wynik != przypadek.chciany {
			t.Errorf("wlasciciel(%q, %q) = %q, chciano %q",
				przypadek.cel, przypadek.tresc, wynik, przypadek.chciany)
		}
	}
}

// Nazwa do testu idzie do polecenia jako argument, wiec musi byc nazwa.
func TestNazwaDoTestuJestSprawdzana(t *testing.T) {
	for _, nazwa := range []string{"", "-4", "host name", "a/b", "host;reboot", ".."} {
		if PoprawnaNazwaDoTestu(nazwa) {
			t.Errorf("przyjeto nazwe %q", nazwa)
		}
	}
	for _, nazwa := range []string{"ipa.flotestro.test", "host", "_kerberos._tcp.flotestro.test", "a-b.test."} {
		if !PoprawnaNazwaDoTestu(nazwa) {
			t.Errorf("odrzucono nazwe %q", nazwa)
		}
	}
}
