package dns

import "testing"

// Output copied from a host of the test fleet.
const resolvectlOutput = `Global
         Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 192.168.56.50
       DNS Servers: 192.168.56.50
        DNS Domain: ~flotestro.test

Link 2 (enp0s3)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute LLMNR=resolve -mDNS -DNSOverTLS
                    DNSSEC=no/unsupported
Current DNS Server: 10.0.2.3
       DNS Servers: 10.0.2.3
        DNS Domain: vcmts-wawPereca-1.vectranet.pl
     Default Route: yes

Link 3 (enp0s8)
    Current Scopes: LLMNR/IPv4 LLMNR/IPv6
         Protocols: -DefaultRoute LLMNR=resolve -mDNS -DNSOverTLS
                    DNSSEC=no/unsupported
     Default Route: no`

// A domain-joined host has the directory server on one link and the
// provider's server on the other. Merging them into one list would hide
// which server answers.
func TestResolverSeparatesServersPerLink(t *testing.T) {
	snapshot := ParseResolvectl(resolvectlOutput)

	if snapshot.Mode != "stub" {
		t.Errorf("mode = %q", snapshot.Mode)
	}
	if len(snapshot.Servers) != 1 || snapshot.Servers[0] != "192.168.56.50" {
		t.Errorf("global servers = %v", snapshot.Servers)
	}
	if len(snapshot.Links) != 2 {
		t.Fatalf("links = %d", len(snapshot.Links))
	}
	byName := map[string]Link{}
	for _, link := range snapshot.Links {
		byName[link.Name] = link
	}
	if len(byName["enp0s3"].Servers) != 1 || byName["enp0s3"].Servers[0] != "10.0.2.3" {
		t.Errorf("enp0s3 servers = %v", byName["enp0s3"].Servers)
	}
	// A link without its own server must not inherit somebody else's.
	if len(byName["enp0s8"].Servers) != 0 {
		t.Errorf("enp0s8 servers = %v", byName["enp0s8"].Servers)
	}
	// The default route decides which link answers names outside its
	// domains.
	if byName["enp0s3"].DefaultRoute == nil || !*byName["enp0s3"].DefaultRoute {
		t.Errorf("enp0s3 default route = %v", byName["enp0s3"].DefaultRoute)
	}
	if byName["enp0s8"].DefaultRoute == nil || *byName["enp0s8"].DefaultRoute {
		t.Errorf("enp0s8 default route = %v", byName["enp0s8"].DefaultRoute)
	}
	// Protocols wrap onto two rows, so the link's DNSSEC is in the second.
	if byName["enp0s3"].DNSSEC != "no/unsupported" || byName["enp0s3"].DNSOverTLS != "no" {
		t.Errorf("enp0s3 protocols = %q / %q", byName["enp0s3"].DNSSEC, byName["enp0s3"].DNSOverTLS)
	}
	if snapshot.Links[0].Index != 2 {
		t.Errorf("link index = %d", snapshot.Links[0].Index)
	}
}

func TestResolverFileReadsServersAndDomains(t *testing.T) {
	content := `# Generated by dhcpcd from eth0.dhcp, eth0.ra
domain vcmts-wawPereca-1.vectranet.pl
nameserver 10.0.2.3
nameserver fd17:625c:f037:2::3
search flotestro.test example.test`
	servers, domains := ParseResolvConf(content)
	if len(servers) != 2 || servers[1] != "fd17:625c:f037:2::3" {
		t.Errorf("servers = %v", servers)
	}
	if len(domains) != 3 {
		t.Errorf("domains = %v", domains)
	}
}

// The file owner decides whether the panel may change anything: a file
// belonging to a service gets overwritten anyway.
func TestFileOwnerIsRecognised(t *testing.T) {
	cases := []struct {
		target, content, want string
	}{
		{"../run/systemd/resolve/stub-resolv.conf", "", OwnerResolved},
		{"/run/NetworkManager/resolv.conf", "", OwnerNetworkManager},
		{"", "# Generated by dhcpcd from eth0.dhcp\nnameserver 10.0.2.3", OwnerDHCP},
		{"", "# This file is managed by man:systemd-resolved(8)", OwnerResolved},
		{"", "nameserver 10.0.0.1", OwnerManual},
		// An empty file says nothing about the owner, and guessing would
		// encourage the panel to write over something it does not understand.
		{"", "", OwnerUnknown},
	}
	for _, tc := range cases {
		if got := ResolvConfOwner(tc.target, tc.content); got != tc.want {
			t.Errorf("owner(%q, %q) = %q, want %q",
				tc.target, tc.content, got, tc.want)
		}
	}
}

// The test name goes to the command as an argument, so it has to be a name.
func TestTestNameIsValidated(t *testing.T) {
	for _, name := range []string{"", "-4", "host name", "a/b", "host;reboot", ".."} {
		if ValidTestName(name) {
			t.Errorf("accepted name %q", name)
		}
	}
	for _, name := range []string{"ipa.flotestro.test", "host", "_kerberos._tcp.flotestro.test", "a-b.test."} {
		if !ValidTestName(name) {
			t.Errorf("rejected name %q", name)
		}
	}
}
