// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: flotestro/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ultherego/flotestro/internal/genproto/flotestro/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EnrollmentServiceName is the fully-qualified name of the EnrollmentService service.
	EnrollmentServiceName = "flotestro.agent.v1.EnrollmentService"
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "flotestro.agent.v1.AgentService"
	// RelayServiceName is the fully-qualified name of the RelayService service.
	RelayServiceName = "flotestro.agent.v1.RelayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EnrollmentServiceEnrollProcedure is the fully-qualified name of the EnrollmentService's Enroll
	// RPC.
	EnrollmentServiceEnrollProcedure = "/flotestro.agent.v1.EnrollmentService/Enroll"
	// AgentServiceConnectProcedure is the fully-qualified name of the AgentService's Connect RPC.
	AgentServiceConnectProcedure = "/flotestro.agent.v1.AgentService/Connect"
	// AgentServiceRenewCertificateProcedure is the fully-qualified name of the AgentService's
	// RenewCertificate RPC.
	AgentServiceRenewCertificateProcedure = "/flotestro.agent.v1.AgentService/RenewCertificate"
	// AgentServicePingProcedure is the fully-qualified name of the AgentService's Ping RPC.
	AgentServicePingProcedure = "/flotestro.agent.v1.AgentService/Ping"
	// AgentServiceFetchSecretProcedure is the fully-qualified name of the AgentService's FetchSecret
	// RPC.
	AgentServiceFetchSecretProcedure = "/flotestro.agent.v1.AgentService/FetchSecret"
	// RelayServiceRenewCertificateProcedure is the fully-qualified name of the RelayService's
	// RenewCertificate RPC.
	RelayServiceRenewCertificateProcedure = "/flotestro.agent.v1.RelayService/RenewCertificate"
	// RelayServicePingProcedure is the fully-qualified name of the RelayService's Ping RPC.
	RelayServicePingProcedure = "/flotestro.agent.v1.RelayService/Ping"
	// RelayServiceProxyEnrollProcedure is the fully-qualified name of the RelayService's ProxyEnroll
	// RPC.
	RelayServiceProxyEnrollProcedure = "/flotestro.agent.v1.RelayService/ProxyEnroll"
)

// EnrollmentServiceClient is a client for the flotestro.agent.v1.EnrollmentService service.
type EnrollmentServiceClient interface {
	Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewEnrollmentServiceClient constructs a client for the flotestro.agent.v1.EnrollmentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEnrollmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EnrollmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	enrollmentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("EnrollmentService").Methods()
	return &enrollmentServiceClient{
		enroll: connect.NewClient[v1.EnrollRequest, v1.EnrollResponse](
			httpClient,
			baseURL+EnrollmentServiceEnrollProcedure,
			connect.WithSchema(enrollmentServiceMethods.ByName("Enroll")),
			connect.WithClientOptions(opts...),
		),
	}
}

// enrollmentServiceClient implements EnrollmentServiceClient.
type enrollmentServiceClient struct {
	enroll *connect.Client[v1.EnrollRequest, v1.EnrollResponse]
}

// Enroll calls flotestro.agent.v1.EnrollmentService.Enroll.
func (c *enrollmentServiceClient) Enroll(ctx context.Context, req *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return c.enroll.CallUnary(ctx, req)
}

// EnrollmentServiceHandler is an implementation of the flotestro.agent.v1.EnrollmentService
// service.
type EnrollmentServiceHandler interface {
	Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewEnrollmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEnrollmentServiceHandler(svc EnrollmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	enrollmentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("EnrollmentService").Methods()
	enrollmentServiceEnrollHandler := connect.NewUnaryHandler(
		EnrollmentServiceEnrollProcedure,
		svc.Enroll,
		connect.WithSchema(enrollmentServiceMethods.ByName("Enroll")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flotestro.agent.v1.EnrollmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EnrollmentServiceEnrollProcedure:
			enrollmentServiceEnrollHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEnrollmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEnrollmentServiceHandler struct{}

func (UnimplementedEnrollmentServiceHandler) Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.EnrollmentService.Enroll is not implemented"))
}

// AgentServiceClient is a client for the flotestro.agent.v1.AgentService service.
type AgentServiceClient interface {
	Connect(context.Context) *connect.BidiStreamForClient[v1.AgentMessage, v1.ServerMessage]
	// RenewCertificate exchanges a new CSR for a certificate. The identity
	// comes from the current client certificate, not from the request body, so
	// a renewal neither requires nor may use an enrollment token: the token is
	// a one-time entry for a host without an identity.
	RenewCertificate(context.Context, *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error)
	// Ping checks connectivity with the centre without any side effect.
	//
	// A relay needs a way to tell that the link is back before it sends
	// anything that matters. Probing the link by sending real messages costs
	// losing those messages if the link does not work after all.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// FetchSecret issues a secret value for the duration of one job.
	//
	// The value does not travel in the job envelope: the envelope carries only
	// a reference, and the host fetches the content only when it starts the
	// operation. Thanks to that the value is neither in the job, nor in the
	// audit log, nor in the inventory - it is only in the store and briefly in
	// the host's memory.
	FetchSecret(context.Context, *connect.Request[v1.FetchSecretRequest]) (*connect.Response[v1.FetchSecretResponse], error)
}

// NewAgentServiceClient constructs a client for the flotestro.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		connect: connect.NewClient[v1.AgentMessage, v1.ServerMessage](
			httpClient,
			baseURL+AgentServiceConnectProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		renewCertificate: connect.NewClient[v1.RenewCertificateRequest, v1.RenewCertificateResponse](
			httpClient,
			baseURL+AgentServiceRenewCertificateProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RenewCertificate")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+AgentServicePingProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		fetchSecret: connect.NewClient[v1.FetchSecretRequest, v1.FetchSecretResponse](
			httpClient,
			baseURL+AgentServiceFetchSecretProcedure,
			connect.WithSchema(agentServiceMethods.ByName("FetchSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	connect          *connect.Client[v1.AgentMessage, v1.ServerMessage]
	renewCertificate *connect.Client[v1.RenewCertificateRequest, v1.RenewCertificateResponse]
	ping             *connect.Client[v1.PingRequest, v1.PingResponse]
	fetchSecret      *connect.Client[v1.FetchSecretRequest, v1.FetchSecretResponse]
}

// Connect calls flotestro.agent.v1.AgentService.Connect.
func (c *agentServiceClient) Connect(ctx context.Context) *connect.BidiStreamForClient[v1.AgentMessage, v1.ServerMessage] {
	return c.connect.CallBidiStream(ctx)
}

// RenewCertificate calls flotestro.agent.v1.AgentService.RenewCertificate.
func (c *agentServiceClient) RenewCertificate(ctx context.Context, req *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error) {
	return c.renewCertificate.CallUnary(ctx, req)
}

// Ping calls flotestro.agent.v1.AgentService.Ping.
func (c *agentServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// FetchSecret calls flotestro.agent.v1.AgentService.FetchSecret.
func (c *agentServiceClient) FetchSecret(ctx context.Context, req *connect.Request[v1.FetchSecretRequest]) (*connect.Response[v1.FetchSecretResponse], error) {
	return c.fetchSecret.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the flotestro.agent.v1.AgentService service.
type AgentServiceHandler interface {
	Connect(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ServerMessage]) error
	// RenewCertificate exchanges a new CSR for a certificate. The identity
	// comes from the current client certificate, not from the request body, so
	// a renewal neither requires nor may use an enrollment token: the token is
	// a one-time entry for a host without an identity.
	RenewCertificate(context.Context, *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error)
	// Ping checks connectivity with the centre without any side effect.
	//
	// A relay needs a way to tell that the link is back before it sends
	// anything that matters. Probing the link by sending real messages costs
	// losing those messages if the link does not work after all.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// FetchSecret issues a secret value for the duration of one job.
	//
	// The value does not travel in the job envelope: the envelope carries only
	// a reference, and the host fetches the content only when it starts the
	// operation. Thanks to that the value is neither in the job, nor in the
	// audit log, nor in the inventory - it is only in the store and briefly in
	// the host's memory.
	FetchSecret(context.Context, *connect.Request[v1.FetchSecretRequest]) (*connect.Response[v1.FetchSecretResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceConnectHandler := connect.NewBidiStreamHandler(
		AgentServiceConnectProcedure,
		svc.Connect,
		connect.WithSchema(agentServiceMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRenewCertificateHandler := connect.NewUnaryHandler(
		AgentServiceRenewCertificateProcedure,
		svc.RenewCertificate,
		connect.WithSchema(agentServiceMethods.ByName("RenewCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	agentServicePingHandler := connect.NewUnaryHandler(
		AgentServicePingProcedure,
		svc.Ping,
		connect.WithSchema(agentServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceFetchSecretHandler := connect.NewUnaryHandler(
		AgentServiceFetchSecretProcedure,
		svc.FetchSecret,
		connect.WithSchema(agentServiceMethods.ByName("FetchSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flotestro.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceConnectProcedure:
			agentServiceConnectHandler.ServeHTTP(w, r)
		case AgentServiceRenewCertificateProcedure:
			agentServiceRenewCertificateHandler.ServeHTTP(w, r)
		case AgentServicePingProcedure:
			agentServicePingHandler.ServeHTTP(w, r)
		case AgentServiceFetchSecretProcedure:
			agentServiceFetchSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) Connect(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.AgentService.Connect is not implemented"))
}

func (UnimplementedAgentServiceHandler) RenewCertificate(context.Context, *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.AgentService.RenewCertificate is not implemented"))
}

func (UnimplementedAgentServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.AgentService.Ping is not implemented"))
}

func (UnimplementedAgentServiceHandler) FetchSecret(context.Context, *connect.Request[v1.FetchSecretRequest]) (*connect.Response[v1.FetchSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.AgentService.FetchSecret is not implemented"))
}

// RelayServiceClient is a client for the flotestro.agent.v1.RelayService service.
type RelayServiceClient interface {
	// RenewCertificate exchanges the relay's CSR for a new certificate. The
	// identity comes from the current client certificate, not from the request
	// body.
	RenewCertificate(context.Context, *connect.Request[v1.RenewRelayCertificateRequest]) (*connect.Response[v1.RenewRelayCertificateResponse], error)
	// Ping checks the relay's connectivity with the centre and refreshes its
	// last presence.
	Ping(context.Context, *connect.Request[v1.RelayPingRequest]) (*connect.Response[v1.RelayPingResponse], error)
	// ProxyEnroll forwards a host enrollment from an isolated site.
	//
	// The relay signs nothing itself: the fleet CA stays in the centre. The
	// relay is the TLS terminator, so it sees the token - and that is exactly
	// why the enrollment goes over its mTLS channel, not the public enrollment
	// endpoint. The centre then knows which site attests to this enrollment
	// and can refuse a token carried elsewhere.
	ProxyEnroll(context.Context, *connect.Request[v1.ProxyEnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewRelayServiceClient constructs a client for the flotestro.agent.v1.RelayService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRelayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RelayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	relayServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("RelayService").Methods()
	return &relayServiceClient{
		renewCertificate: connect.NewClient[v1.RenewRelayCertificateRequest, v1.RenewRelayCertificateResponse](
			httpClient,
			baseURL+RelayServiceRenewCertificateProcedure,
			connect.WithSchema(relayServiceMethods.ByName("RenewCertificate")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1.RelayPingRequest, v1.RelayPingResponse](
			httpClient,
			baseURL+RelayServicePingProcedure,
			connect.WithSchema(relayServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		proxyEnroll: connect.NewClient[v1.ProxyEnrollRequest, v1.EnrollResponse](
			httpClient,
			baseURL+RelayServiceProxyEnrollProcedure,
			connect.WithSchema(relayServiceMethods.ByName("ProxyEnroll")),
			connect.WithClientOptions(opts...),
		),
	}
}

// relayServiceClient implements RelayServiceClient.
type relayServiceClient struct {
	renewCertificate *connect.Client[v1.RenewRelayCertificateRequest, v1.RenewRelayCertificateResponse]
	ping             *connect.Client[v1.RelayPingRequest, v1.RelayPingResponse]
	proxyEnroll      *connect.Client[v1.ProxyEnrollRequest, v1.EnrollResponse]
}

// RenewCertificate calls flotestro.agent.v1.RelayService.RenewCertificate.
func (c *relayServiceClient) RenewCertificate(ctx context.Context, req *connect.Request[v1.RenewRelayCertificateRequest]) (*connect.Response[v1.RenewRelayCertificateResponse], error) {
	return c.renewCertificate.CallUnary(ctx, req)
}

// Ping calls flotestro.agent.v1.RelayService.Ping.
func (c *relayServiceClient) Ping(ctx context.Context, req *connect.Request[v1.RelayPingRequest]) (*connect.Response[v1.RelayPingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// ProxyEnroll calls flotestro.agent.v1.RelayService.ProxyEnroll.
func (c *relayServiceClient) ProxyEnroll(ctx context.Context, req *connect.Request[v1.ProxyEnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return c.proxyEnroll.CallUnary(ctx, req)
}

// RelayServiceHandler is an implementation of the flotestro.agent.v1.RelayService service.
type RelayServiceHandler interface {
	// RenewCertificate exchanges the relay's CSR for a new certificate. The
	// identity comes from the current client certificate, not from the request
	// body.
	RenewCertificate(context.Context, *connect.Request[v1.RenewRelayCertificateRequest]) (*connect.Response[v1.RenewRelayCertificateResponse], error)
	// Ping checks the relay's connectivity with the centre and refreshes its
	// last presence.
	Ping(context.Context, *connect.Request[v1.RelayPingRequest]) (*connect.Response[v1.RelayPingResponse], error)
	// ProxyEnroll forwards a host enrollment from an isolated site.
	//
	// The relay signs nothing itself: the fleet CA stays in the centre. The
	// relay is the TLS terminator, so it sees the token - and that is exactly
	// why the enrollment goes over its mTLS channel, not the public enrollment
	// endpoint. The centre then knows which site attests to this enrollment
	// and can refuse a token carried elsewhere.
	ProxyEnroll(context.Context, *connect.Request[v1.ProxyEnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewRelayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRelayServiceHandler(svc RelayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	relayServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("RelayService").Methods()
	relayServiceRenewCertificateHandler := connect.NewUnaryHandler(
		RelayServiceRenewCertificateProcedure,
		svc.RenewCertificate,
		connect.WithSchema(relayServiceMethods.ByName("RenewCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	relayServicePingHandler := connect.NewUnaryHandler(
		RelayServicePingProcedure,
		svc.Ping,
		connect.WithSchema(relayServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceProxyEnrollHandler := connect.NewUnaryHandler(
		RelayServiceProxyEnrollProcedure,
		svc.ProxyEnroll,
		connect.WithSchema(relayServiceMethods.ByName("ProxyEnroll")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flotestro.agent.v1.RelayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RelayServiceRenewCertificateProcedure:
			relayServiceRenewCertificateHandler.ServeHTTP(w, r)
		case RelayServicePingProcedure:
			relayServicePingHandler.ServeHTTP(w, r)
		case RelayServiceProxyEnrollProcedure:
			relayServiceProxyEnrollHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRelayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRelayServiceHandler struct{}

func (UnimplementedRelayServiceHandler) RenewCertificate(context.Context, *connect.Request[v1.RenewRelayCertificateRequest]) (*connect.Response[v1.RenewRelayCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.RelayService.RenewCertificate is not implemented"))
}

func (UnimplementedRelayServiceHandler) Ping(context.Context, *connect.Request[v1.RelayPingRequest]) (*connect.Response[v1.RelayPingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.RelayService.Ping is not implemented"))
}

func (UnimplementedRelayServiceHandler) ProxyEnroll(context.Context, *connect.Request[v1.ProxyEnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.RelayService.ProxyEnroll is not implemented"))
}
