// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: flotestro/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ultherego/flotestro/internal/genproto/flotestro/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EnrollmentServiceName is the fully-qualified name of the EnrollmentService service.
	EnrollmentServiceName = "flotestro.agent.v1.EnrollmentService"
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "flotestro.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EnrollmentServiceEnrollProcedure is the fully-qualified name of the EnrollmentService's Enroll
	// RPC.
	EnrollmentServiceEnrollProcedure = "/flotestro.agent.v1.EnrollmentService/Enroll"
	// AgentServiceConnectProcedure is the fully-qualified name of the AgentService's Connect RPC.
	AgentServiceConnectProcedure = "/flotestro.agent.v1.AgentService/Connect"
	// AgentServiceRenewCertificateProcedure is the fully-qualified name of the AgentService's
	// RenewCertificate RPC.
	AgentServiceRenewCertificateProcedure = "/flotestro.agent.v1.AgentService/RenewCertificate"
)

// EnrollmentServiceClient is a client for the flotestro.agent.v1.EnrollmentService service.
type EnrollmentServiceClient interface {
	Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewEnrollmentServiceClient constructs a client for the flotestro.agent.v1.EnrollmentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEnrollmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EnrollmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	enrollmentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("EnrollmentService").Methods()
	return &enrollmentServiceClient{
		enroll: connect.NewClient[v1.EnrollRequest, v1.EnrollResponse](
			httpClient,
			baseURL+EnrollmentServiceEnrollProcedure,
			connect.WithSchema(enrollmentServiceMethods.ByName("Enroll")),
			connect.WithClientOptions(opts...),
		),
	}
}

// enrollmentServiceClient implements EnrollmentServiceClient.
type enrollmentServiceClient struct {
	enroll *connect.Client[v1.EnrollRequest, v1.EnrollResponse]
}

// Enroll calls flotestro.agent.v1.EnrollmentService.Enroll.
func (c *enrollmentServiceClient) Enroll(ctx context.Context, req *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return c.enroll.CallUnary(ctx, req)
}

// EnrollmentServiceHandler is an implementation of the flotestro.agent.v1.EnrollmentService
// service.
type EnrollmentServiceHandler interface {
	Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewEnrollmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEnrollmentServiceHandler(svc EnrollmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	enrollmentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("EnrollmentService").Methods()
	enrollmentServiceEnrollHandler := connect.NewUnaryHandler(
		EnrollmentServiceEnrollProcedure,
		svc.Enroll,
		connect.WithSchema(enrollmentServiceMethods.ByName("Enroll")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flotestro.agent.v1.EnrollmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EnrollmentServiceEnrollProcedure:
			enrollmentServiceEnrollHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEnrollmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEnrollmentServiceHandler struct{}

func (UnimplementedEnrollmentServiceHandler) Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.EnrollmentService.Enroll is not implemented"))
}

// AgentServiceClient is a client for the flotestro.agent.v1.AgentService service.
type AgentServiceClient interface {
	Connect(context.Context) *connect.BidiStreamForClient[v1.AgentMessage, v1.ServerMessage]
	// RenewCertificate wymienia nowy CSR na certyfikat. Tozsamosc pochodzi
	// z obecnego certyfikatu klienta, a nie z tresci zadania, wiec odnowienie
	// nie wymaga i nie moze uzywac tokenu enrollmentu: token jest jednorazowym
	// wejsciem dla hosta bez tozsamosci.
	RenewCertificate(context.Context, *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error)
}

// NewAgentServiceClient constructs a client for the flotestro.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		connect: connect.NewClient[v1.AgentMessage, v1.ServerMessage](
			httpClient,
			baseURL+AgentServiceConnectProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		renewCertificate: connect.NewClient[v1.RenewCertificateRequest, v1.RenewCertificateResponse](
			httpClient,
			baseURL+AgentServiceRenewCertificateProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RenewCertificate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	connect          *connect.Client[v1.AgentMessage, v1.ServerMessage]
	renewCertificate *connect.Client[v1.RenewCertificateRequest, v1.RenewCertificateResponse]
}

// Connect calls flotestro.agent.v1.AgentService.Connect.
func (c *agentServiceClient) Connect(ctx context.Context) *connect.BidiStreamForClient[v1.AgentMessage, v1.ServerMessage] {
	return c.connect.CallBidiStream(ctx)
}

// RenewCertificate calls flotestro.agent.v1.AgentService.RenewCertificate.
func (c *agentServiceClient) RenewCertificate(ctx context.Context, req *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error) {
	return c.renewCertificate.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the flotestro.agent.v1.AgentService service.
type AgentServiceHandler interface {
	Connect(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ServerMessage]) error
	// RenewCertificate wymienia nowy CSR na certyfikat. Tozsamosc pochodzi
	// z obecnego certyfikatu klienta, a nie z tresci zadania, wiec odnowienie
	// nie wymaga i nie moze uzywac tokenu enrollmentu: token jest jednorazowym
	// wejsciem dla hosta bez tozsamosci.
	RenewCertificate(context.Context, *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_flotestro_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceConnectHandler := connect.NewBidiStreamHandler(
		AgentServiceConnectProcedure,
		svc.Connect,
		connect.WithSchema(agentServiceMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRenewCertificateHandler := connect.NewUnaryHandler(
		AgentServiceRenewCertificateProcedure,
		svc.RenewCertificate,
		connect.WithSchema(agentServiceMethods.ByName("RenewCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flotestro.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceConnectProcedure:
			agentServiceConnectHandler.ServeHTTP(w, r)
		case AgentServiceRenewCertificateProcedure:
			agentServiceRenewCertificateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) Connect(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.AgentService.Connect is not implemented"))
}

func (UnimplementedAgentServiceHandler) RenewCertificate(context.Context, *connect.Request[v1.RenewCertificateRequest]) (*connect.Response[v1.RenewCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flotestro.agent.v1.AgentService.RenewCertificate is not implemented"))
}
