// Package metrics exposes the state of the panel in the Prometheus text
// format.
//
// The document requires SLOs and alerts for the age of the queue, the
// dispatch latency, the number of active sessions, task failures and
// certificate validity. Without them the only way to check the panel is to
// look into /proc and into the database, which cannot be done in a customer's
// installation.
//
// The format is generated by hand: the set of metrics is small and stable,
// and every dependency on a path that has to work exactly when the panel is
// in trouble is a cost in itself.
package metrics

import (
	"context"
	"fmt"
	"runtime"
	"sort"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ultherego/flotestro/internal/pki"
)

// SessionCounter gives the number of active agent sessions of this instance.
type SessionCounter interface {
	Count() int
}

// CertificateSource gives the validity time of the CA certificate.
type CertificateSource interface {
	NotAfter() time.Time
}

type Collector struct {
	pool     *pgxpool.Pool
	sessions SessionCounter
	ca       CertificateSource
	// authorities describes the whole trust set, if the installation manages one.
	authorities func() []pki.Authority
	gateway     string
	started     time.Time
}

// WithAuthorities adds metrics for every CA in the trust set.
func (c *Collector) WithAuthorities(source func() []pki.Authority) *Collector {
	c.authorities = source
	return c
}

func NewCollector(pool *pgxpool.Pool, sessions SessionCounter, ca CertificateSource,
	gatewayID string) *Collector {
	return &Collector{pool: pool, sessions: sessions, ca: ca,
		gateway: gatewayID, started: time.Now()}
}

// sample is a single value with labels.
type sample struct {
	labels map[string]string
	value  float64
}

// metric groups values under one name together with a description.
type metric struct {
	name    string
	help    string
	kind    string
	samples []sample
}

// Gather collects the state of the panel. A failure of a single query must
// not extinguish the whole answer: a metric that could not be determined is
// skipped rather than zeroed - zero would mean "zero was measured".
func (c *Collector) Gather(ctx context.Context) []byte {
	metrics := []metric{
		{
			name: "flotestro_build_info", kind: "gauge",
			help:    "The panel instance; the gateway label distinguishes processes in a multi-gateway installation.",
			samples: []sample{{labels: map[string]string{"gateway": c.gateway}, value: 1}},
		},
		{
			name: "flotestro_uptime_seconds", kind: "gauge",
			help:    "How long the panel process has been running.",
			samples: []sample{{value: time.Since(c.started).Seconds()}},
		},
	}

	if c.sessions != nil {
		metrics = append(metrics, metric{
			name: "flotestro_agent_sessions_active", kind: "gauge",
			help: "Agent sessions held by this instance of the panel.",
			samples: []sample{{
				labels: map[string]string{"gateway": c.gateway},
				value:  float64(c.sessions.Count()),
			}},
		})
	}

	if c.ca != nil {
		if notAfter := c.ca.NotAfter(); !notAfter.IsZero() {
			metrics = append(metrics, metric{
				name: "flotestro_ca_certificate_expires_in_seconds", kind: "gauge",
				help:    "Time until the CA signing agent certificates expires.",
				samples: []sample{{value: time.Until(notAfter).Seconds()}},
			})
		}
	}
	if c.authorities != nil {
		// A withdrawn CA has to be visible too: its expiry cuts off the hosts
		// that did not manage to move to the new one.
		var samples []sample
		for _, ca := range c.authorities() {
			samples = append(samples, sample{
				labels: map[string]string{"state": ca.State, "serial": ca.Serial},
				value:  time.Until(ca.NotAfter).Seconds(),
			})
		}
		if len(samples) > 0 {
			metrics = append(metrics, metric{
				name: "flotestro_trust_authority_expires_in_seconds", kind: "gauge",
				help:    "Time until every CA in the fleet's trust set expires.",
				samples: samples,
			})
		}
	}

	metrics = append(metrics, c.runtimeMetrics()...)
	metrics = append(metrics, c.databaseMetrics(ctx)...)
	var b strings.Builder
	b.Write(render(metrics))
	// The instruments measured at the point of the event come last: they
	// belong to this process, the rest to the database.
	Default.render(&b)
	return []byte(b.String())
}

func (c *Collector) runtimeMetrics() []metric {
	var memory runtime.MemStats
	runtime.ReadMemStats(&memory)
	return []metric{
		{
			name: "flotestro_goroutines", kind: "gauge",
			help:    "The number of goroutines of the panel process.",
			samples: []sample{{value: float64(runtime.NumGoroutine())}},
		},
		{
			name: "flotestro_memory_bytes", kind: "gauge",
			help:    "Memory reserved by the panel process.",
			samples: []sample{{value: float64(memory.Sys)}},
		},
	}
}

// databaseMetrics reads the state of the fleet and the queue. The queries are
// aggregates over indexed columns; a scrape must not be a load comparable
// with the panel's own work.
func (c *Collector) databaseMetrics(ctx context.Context) []metric {
	if c.pool == nil {
		return nil
	}
	queryCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	var result []metric

	if grouped, err := c.groupCount(queryCtx,
		`select connection_state, count(*) from hosts group by 1`); err == nil {
		result = append(result, metric{
			name: "flotestro_hosts", kind: "gauge",
			help:    "The fleet's hosts by connection state.",
			samples: labelled("connection_state", grouped),
		})
	}

	if grouped, err := c.groupCount(queryCtx,
		`select state, count(*) from jobs where created_at > now() - interval '24 hours' group by 1`); err == nil {
		result = append(result, metric{
			name: "flotestro_jobs", kind: "gauge",
			help:    "Tasks from the last day by state.",
			samples: labelled("state", grouped),
		})
	}

	// The age of the oldest task in the queue is a signal that dispatching
	// has stopped keeping up. The number of tasks alone does not show it.
	var queueAge *float64
	if err := c.pool.QueryRow(queryCtx,
		`select extract(epoch from now() - min(created_at)) from jobs where state = 'queued'`).
		Scan(&queueAge); err == nil {
		value := 0.0
		if queueAge != nil {
			value = *queueAge
		}
		result = append(result, metric{
			name: "flotestro_job_queue_age_seconds", kind: "gauge",
			help:    "The age of the oldest task waiting to be dispatched.",
			samples: []sample{{value: value}},
		})
	}

	// We measure the dispatch latency from the creation of a task to handing
	// it over to the agent. The moment execution starts on the host is not
	// reported by the agent, so it is not here - instead of guessing we
	// measure what the panel actually observes.
	var avg, max *float64
	if err := c.pool.QueryRow(queryCtx, `
		select avg(extract(epoch from a.dispatched_at - j.created_at)),
		       max(extract(epoch from a.dispatched_at - j.created_at))
		from job_attempts a
		join jobs j on j.id = a.job_id
		where a.dispatched_at > now() - interval '15 minutes'`).Scan(&avg, &max); err == nil {
		if avg != nil {
			result = append(result, metric{
				name: "flotestro_dispatch_latency_seconds_avg", kind: "gauge",
				help:    "The average time from creating a task to handing it to the agent, over the last 15 minutes.",
				samples: []sample{{value: *avg}},
			})
		}
		if max != nil {
			result = append(result, metric{
				name: "flotestro_dispatch_latency_seconds_max", kind: "gauge",
				help:    "The longest time from creating a task to handing it to the agent, over the last 15 minutes.",
				samples: []sample{{value: *max}},
			})
		}
	}

	if grouped, err := c.groupCount(queryCtx, `
		select status, count(*) from job_attempts
		where finished_at > now() - interval '24 hours' group by 1`); err == nil {
		result = append(result, metric{
			name: "flotestro_task_results", kind: "gauge",
			help:    "Task results from the last day by status.",
			samples: labelled("status", grouped),
		})
	}

	return append(result, c.campaignMetrics(queryCtx)...)
}

// campaignMetrics show the machinery of a fleet-wide change: the campaigns
// under way, the fate of their hosts and the capacity that governs them.
//
// Without them a campaign stopped on a budget or on somebody else's lock
// looks from the outside exactly like a campaign that is moving - and those
// are two different situations, only one of which calls for a reaction.
//
// The labels are closed: state, operation, reason code and budget key. The
// host name is not a label here - the fleet grows, and the number of time
// series is not to grow with it.
func (c *Collector) campaignMetrics(ctx context.Context) []metric {
	var result []metric

	if samples, err := c.labelPairs(ctx, `
		select state, action_type, count(*) from campaigns
		 where state in ('planning', 'planned', 'awaiting_approval', 'canary', 'running', 'paused')
		 group by 1, 2`, "state", "action"); err == nil {
		result = append(result, metric{
			name: "flotestro_campaigns_active", kind: "gauge",
			help:    "Campaigns under way by state and operation.",
			samples: samples,
		})
	}

	// The reason code matters here as much as the state: a host held back by
	// a lack of capacity and a host without the required adapter are both
	// "did not start", and they mean different things and call for different
	// actions.
	if samples, err := c.labelPairs(ctx, `
		select t.state, coalesce(nullif(t.error_code, ''), 'none'), count(*)
		  from campaign_targets t
		  join campaigns c on c.id = t.campaign_id
		 where c.state in ('planning', 'planned', 'awaiting_approval', 'canary', 'running', 'paused')
		 group by 1, 2`, "state", "reason_code"); err == nil {
		result = append(result, metric{
			name: "flotestro_campaign_targets", kind: "gauge",
			help:    "The hosts of campaigns under way by state and reason code.",
			samples: samples,
		})
	}

	// Capacity and usage in one series, told apart by a label: without the
	// capacity the usage alone does not say whether the budget is at its
	// limit.
	if samples, err := c.budgetSamples(ctx); err == nil && len(samples) > 0 {
		result = append(result, metric{
			name: "flotestro_budget_tokens", kind: "gauge",
			help:    "Budget tokens: capacity, usage and the number of claimants waiting.",
			samples: samples,
		})
	}

	// The longest current wait for capacity. There is no histogram here: the
	// collector renders series straight from the queries, and an invented
	// histogram with buckets computed after the fact would lie about the
	// distribution.
	if samples, err := c.budgetWaits(ctx); err == nil && len(samples) > 0 {
		result = append(result, metric{
			name: "flotestro_budget_wait_seconds_max", kind: "gauge",
			help:    "The longest current wait for budget capacity.",
			samples: samples,
		})
	}

	// The lag of the durable trail: how old the oldest unpublished event is.
	// A publisher that stopped shows up here long before anyone notices a
	// screen that no longer refreshes.
	if samples, err := c.outboxLag(ctx); err == nil {
		result = append(result, metric{
			name: "flotestro_outbox_lag_seconds", kind: "gauge",
			help:    "Age of the oldest event of the durable trail not published yet, by event type.",
			samples: samples,
		})
	}
	return result
}

// outboxLag measures the unpublished part of the trail. A type with nothing
// waiting reports zero: that is a measured zero, not a missing value.
func (c *Collector) outboxLag(ctx context.Context) ([]sample, error) {
	rows, err := c.pool.Query(ctx, `
		select event_type, extract(epoch from now() - min(occurred_at))
		  from outbox_events
		 where published_at is null
		 group by 1`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	samples := []sample{}
	for rows.Next() {
		var eventType string
		var lag float64
		if err := rows.Scan(&eventType, &lag); err != nil {
			return nil, err
		}
		samples = append(samples, sample{labels: map[string]string{"event_type": eventType}, value: lag})
	}
	if len(samples) == 0 {
		samples = append(samples, sample{labels: map[string]string{"event_type": "none"}, value: 0})
	}
	return samples, rows.Err()
}

// labelPairs reads a query with three columns: two labels and a count.
func (c *Collector) labelPairs(ctx context.Context, query, first, second string) ([]sample, error) {
	rows, err := c.pool.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	samples := []sample{}
	for rows.Next() {
		var a, b string
		var count float64
		if err := rows.Scan(&a, &b, &count); err != nil {
			return nil, err
		}
		samples = append(samples, sample{
			labels: map[string]string{first: a, second: b}, value: count,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Slice(samples, func(i, j int) bool {
		if samples[i].labels[first] != samples[j].labels[first] {
			return samples[i].labels[first] < samples[j].labels[first]
		}
		return samples[i].labels[second] < samples[j].labels[second]
	})
	return samples, nil
}

func (c *Collector) budgetSamples(ctx context.Context) ([]sample, error) {
	const query = `
		select l.key, l.capacity,
		       coalesce((select sum(weight) from budget_leases d
		                  where d.key = l.key and d.lease_until > now()), 0),
		       (select count(*) from budget_waiters w
		         where w.key = l.key and w.seen_at > now() - interval '30 seconds')
		  from budget_limits l
		 order by l.key`
	rows, err := c.pool.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	samples := []sample{}
	for rows.Next() {
		var key string
		var capacity, used, waiting float64
		if err := rows.Scan(&key, &capacity, &used, &waiting); err != nil {
			return nil, err
		}
		for status, value := range map[string]float64{
			"capacity": capacity, "used": used, "waiting": waiting,
		} {
			samples = append(samples, sample{
				labels: map[string]string{"budget": key, "status": status},
				value:  value,
			})
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Slice(samples, func(i, j int) bool {
		if samples[i].labels["budget"] != samples[j].labels["budget"] {
			return samples[i].labels["budget"] < samples[j].labels["budget"]
		}
		return samples[i].labels["status"] < samples[j].labels["status"]
	})
	return samples, nil
}

func (c *Collector) budgetWaits(ctx context.Context) ([]sample, error) {
	const query = `
		select key, class, max(extract(epoch from now() - since))
		  from budget_waiters
		 where seen_at > now() - interval '30 seconds'
		 group by 1, 2`
	rows, err := c.pool.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	samples := []sample{}
	for rows.Next() {
		var key, class string
		var seconds float64
		if err := rows.Scan(&key, &class, &seconds); err != nil {
			return nil, err
		}
		samples = append(samples, sample{
			labels: map[string]string{"budget": key, "class": class}, value: seconds,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Slice(samples, func(i, j int) bool {
		return samples[i].labels["budget"] < samples[j].labels["budget"]
	})
	return samples, nil
}

func (c *Collector) groupCount(ctx context.Context, query string) (map[string]float64, error) {
	rows, err := c.pool.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	grouped := map[string]float64{}
	for rows.Next() {
		var key *string
		var count float64
		if err := rows.Scan(&key, &count); err != nil {
			return nil, err
		}
		name := "unknown"
		if key != nil {
			name = *key
		}
		grouped[name] = count
	}
	return grouped, rows.Err()
}

func labelled(name string, grouped map[string]float64) []sample {
	keys := make([]string, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	// A fixed order makes comparing consecutive scrapes by eye easier.
	sort.Strings(keys)

	samples := make([]sample, 0, len(keys))
	for _, key := range keys {
		samples = append(samples, sample{
			labels: map[string]string{name: key}, value: grouped[key],
		})
	}
	return samples
}

func render(metrics []metric) []byte {
	var builder strings.Builder
	for _, m := range metrics {
		fmt.Fprintf(&builder, "# HELP %s %s\n", m.name, m.help)
		fmt.Fprintf(&builder, "# TYPE %s %s\n", m.name, m.kind)
		for _, s := range m.samples {
			builder.WriteString(m.name)
			if len(s.labels) > 0 {
				keys := make([]string, 0, len(s.labels))
				for key := range s.labels {
					keys = append(keys, key)
				}
				sort.Strings(keys)
				pairs := make([]string, 0, len(keys))
				for _, key := range keys {
					// %q would escape the value a second time, giving double
					// backslashes in the result; escape does it once and
					// correctly.
					pairs = append(pairs, fmt.Sprintf(`%s="%s"`, key, escape(s.labels[key])))
				}
				builder.WriteString("{" + strings.Join(pairs, ",") + "}")
			}
			fmt.Fprintf(&builder, " %g\n", s.value)
		}
	}
	return []byte(builder.String())
}

// escape escapes a label value. The name of a state comes from the database
// rather than from the code, so it must not break the format of the
// response.
func escape(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)
	return replacer.Replace(value)
}
